### ISSUE TITLE
Signed mac release

### ISSUE THREAD

**Issue by rgbkrk** [datproject/dat-desktop#120]
I'd love to see the dat releases be signed so they don't come up with the unidentified developer warning. While slightly a miserable process with Apple (the fee is nothing compared to figuring out how they want everything situated), it's working really well for nteract and relieves new users of additional points of friction with new tools. To dat's success!

**Comment by juliangruber** [comment]
Yes! I have a cert and the next release will be signed by it :)

**Comment by juliangruber** [comment]
Afaik we just can't do this on travis, so we'll have to manually sign the releases instead of publishing them as part of our CI

**Comment by rgbkrk** [comment]
Yeah, I've been manually signing our Mac release for nteract. 😞  @lgeiger is hoping to automate it with encrypted Travis tokens - we wouldn't want to run the Xcode build on every PR though, only releases.

**Comment by yoshuawuyts** [comment]
Done (:

**Comment by rgbkrk** [comment]
:tada:
