### ISSUE TITLE
[bug] appveyor failing

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#121]
It seems appveyor is failing for all our windows builds. Travis seems to be fine tho. cc/ @juliangruber any idea what's up?

**Comment by juliangruber** [comment]
yeah, not all of our deps are working on windows yet. see https://github.com/datproject/dat/issues/581.

I left the appveyor CI enabled as a constant reminder, but wouldn't object to disabling it for now.

**Comment by yoshuawuyts** [comment]
ahhh, yeah that makes a lot of sense - thanks for answering :D - I'm cool with leaving it in there as a reminder (:
