### ISSUE TITLE
expose dat-doctor

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#125]
Right now the most frustrating part of Dat is the protocol errors; having a way to debug our protocol from the desktop would be useful.

- discussed in the team call on 03/01/2016

**Comment by juliangruber** [comment]
https://github.com/joehand/dat-doctor/pull/2

**Comment by joehand** [comment]
Published the JS API as dat-doctor 1.2.0.

**Comment by yoshuawuyts** [comment]
I think for the UI we should perhaps make use of a lil modal that displays the info. Near-black background; something like that?

**Comment by yoshuawuyts** [comment]
We could use https://gist.github.com/maxogden/5953535 for a fancy thing; devtools for an MVP (:

**Comment by juliangruber** [comment]
check out https://github.com/datproject/dat-desktop/pull/128 for a devtools MVP

**Comment by juliangruber** [comment]
shall we consider this done and open an issue on a future milestone for a nicer UI version?

**Comment by karissa** [comment]
Sounds good!
