### ISSUE TITLE
switch to multidrive

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#131]
depends on https://github.com/datproject/dat-node/pull/65#issuecomment-270006163. Would make our code a bunch smaller I reckon. Any idea what else this would rely on @juliangruber?

**Comment by juliangruber** [comment]
not that i'm aware of!

**Comment by yoshuawuyts** [comment]
seems like the branch landed, this is now possible (:

**Comment by yoshuawuyts** [comment]
Done (:
