### ISSUE TITLE
'Preview dat' page

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#132]
When you click on a web magnet link like `dat://` and it opens the desktop app, or copy-paste a link into 'import dat' box, there should be a preview page that connects to the swarm in `sparse` mode to collect metadata about the dat.

It should show, at a minimum:

1. file list,
2. size of the dat, 
3. information from dat.json file (title, author)

Then the user can decide to hit OK or hit 'nevermind'. This is similar to what torrent clients do, too!

This will prevent the user from accidentally downloading 40GB of data they don't want, for example, just by clicking on a `dat://` magnet link! :P

**Comment by Kriesse** [comment]
@karissa 👍 

I'll work on a simple mockup. Do you have any screenshots of the torrent clients available? I'll also see if I find any examples.

**Comment by karissa** [comment]
Great, thanks @Kriesse !

We might be able to use some of the design from the datfolder archive page, maybe?

Here's the screen from uTorrent:

![](
https://expertester.files.wordpress.com/2011/12/021.png)

**Comment by juliangruber** [comment]
addressing everything except file selection in https://github.com/datproject/dat-desktop/pull/367

**Comment by Kriesse** [comment]
Closing in favor of #290 and #260

**Comment by karissa** [comment]
👍
