### ISSUE TITLE
Register screen

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#135]
Users should be able to register from the desktop app. Perhaps open a window in the browser? Needs a design

**Comment by Kriesse** [comment]
![image](https://user-images.githubusercontent.com/53684/26926537-6e3958fe-4c4e-11e7-8600-a901d8c2d3bf.png)

**Comment by juliangruber** [comment]
the js part should be done

**Comment by Kriesse** [comment]
Styling done, closing
