### ISSUE TITLE
dat.author needs a default

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#136]
What should we show if there’s no author? "Anonymous"? Or just an empty string?
Can we show "My Dat" when I created the Dat?
https://github.com/datproject/dat-desktop/blob/master/elements/table.js#L230

Right now it looks like this (empty string before the dot):

![image](https://cloud.githubusercontent.com/assets/53684/21818153/9a133f10-d71b-11e6-8b42-63bd004e22b2.png)

**Comment by karissa** [comment]
'Anonymous' vs. 'My Dat' is good.
