### ISSUE TITLE
Create Example for Screenshots/Demo Videos

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#137]
To have consistent marketing materials, we need a good example of Dat Desktop in use, one that we can base all screenshots on, or create short animated gifs for the website, twitter etc.
We need a list of 5 registered/named Dats, they should be the same as the example datasets on datproject.org.

**Comment by maxogden** [comment]
related: https://github.com/datproject/datfolder/issues/368

**Comment by Kriesse** [comment]
Closing, tracking in https://github.com/datproject/datfolder/issues/368
