### ISSUE TITLE
[QA] v1.1.0

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#138]
In order to verify `dat-desktop@1.1.0`  works as expected we should do some Quality Assurance (QA) before releasing.

---
#### crash reporting
- [x] make sure error logs come through (@yoshuawuyts)

#### downloading/installation
- [x] verify http://datproject.org/ has instructions to download the correct latest release
- [x] verify the nice 'disk image' designed background comes up when you open the .dmg
- [x] verify you can drag to applications folder and double click the app to open first try (no right click open)

#### onboarding
- [x] welcome screen should show every time you open the app as long as you have no dats
- [x] make sure you can minimize, full screen, resize, and move the window
- [x] after clicking away welcome screen you should see an empty list with import dat and create new dat

#### importing and creating dats
- [x] click *create new dat* and share a local folder, you should see a new item in the list
- [x] click *import dat* and see if starts to download dat://f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062
- [x] the *progress bar* should correctly show how much progress you have downloaded
- [x] check that *network* (number of peers) is correct 

#### working with dats
- [x] click the *link icon* and it should show a modal and copy the dat link to your clipboard on button click
- [x] click the *open in finder icon* and it should open the folder in Finder.app
- [x] click the *delete icon* and it should pop up a confirmation dialog to remove it
- [x] click the *cancel* button on the delete dialog and check if it cancels the dialog

#### advanced use cases
- [x] share a dat using Dat CLI and try to import it into the desktop
- [x] create new dat in desktop and clone it using Dat CLI
- [x] share dat on another machine using Dat Desktop and import it to your local desktop app
- [x] create new dat in local Dat Desktop and import it on Dat Desktop running on a remote machine

**Comment by juliangruber** [comment]
> verify downloading archives works

what specific archives do we want to test this with? I'm thinking

- lot's of small files
- few big files
- regular archive

**Comment by juliangruber** [comment]
empty state missing (i had archives in there before but deleted them)

![screen shot 2017-01-12 at 12 20 52](https://cloud.githubusercontent.com/assets/10247/21887777/98004216-d8c1-11e6-9fdd-4a840815e86a.png)

**Comment by juliangruber** [comment]
> verify empty states can all be accessed

which empty states are there?

**Comment by juliangruber** [comment]
creating a new dat doesn't work

<img width="829" alt="screen shot 2017-01-12 at 12 25 17" src="https://cloud.githubusercontent.com/assets/10247/21887893/38a03a6e-d8c2-11e6-8d27-9d3f3e216463.png">

**Comment by Kriesse** [comment]
After downloading and opening for the first time, I see a blank app:
![image](https://cloud.githubusercontent.com/assets/53684/21994857/add4f13c-dbd6-11e6-96fd-4f51ddb993ab.png)

**Comment by Kriesse** [comment]
When I tried to close the app, i got this:
![image](https://cloud.githubusercontent.com/assets/53684/21994902/e82945ea-dbd6-11e6-8e36-1ef815ec3ae3.png)

**Comment by Kriesse** [comment]
devtools show this for the blank window:
![image](https://cloud.githubusercontent.com/assets/53684/21994958/397d094a-dbd7-11e6-9dbd-a4cb030ee3bf.png)

**Comment by juliangruber** [comment]
this looks like a browserify problem...it's using absolute paths for the binding files

**Comment by juliangruber** [comment]
> this looks like a browserify problem...it's using absolute paths for the binding files

fix in https://github.com/datproject/dat-desktop/pull/154

**Comment by yoshuawuyts** [comment]
I'm having trouble downloading _very large_ dats, e.g. `f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062` - gets stuck at `0b / 100%`

**Comment by Kriesse** [comment]
ping #155

**Comment by maxogden** [comment]
@Kriesse on " check that number of sources is correct" above, i see this:

![screen shot 2017-02-10 at 11 21 44 am](https://cloud.githubusercontent.com/assets/39759/22840624/20907c90-ef83-11e6-9eb7-8c6a8a0546b3.png)

but I can't see any indication of number of sources

**Comment by juliangruber** [comment]
deleted all comments that have already been addressed

**Comment by Kriesse** [comment]
@yoshuawuyts @juliangruber Should we keep this list open and run through it / extend it for each release?

**Comment by Kriesse** [comment]
Created a new one: https://github.com/datproject/dat-desktop/issues/311
