### ISSUE TITLE
screen flickers when replicating dat while share dialogue is open

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#140]

**Comment by yoshuawuyts** [comment]
Got a screen cap of this? This has happened in the past and is difficult to
recreate

**Comment by juliangruber** [comment]
sure: https://youtu.be/vhkw7a1Cczc

**Comment by juliangruber** [comment]
it's flickering whenever the repo update event fires

**Comment by karissa** [comment]
I wouldn't say this is critical for the stabilize milestone

**Comment by juliangruber** [comment]
when this happens it's almost impossible to dismiss the dialogue, so it's also a functionality bug.

**Comment by yoshuawuyts** [comment]
This bug is really cool; it triggers for me when I hit "copy"

**Comment by yoshuawuyts** [comment]
ah ok, it's because of the nested `onload` stuff - dang, knew I had to try a better design. On it now tho; gonna polish this puppy :sparkles:
