### ISSUE TITLE
error re-importing dat

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#142]
1) Download a dat
2) Remove the dat
3) Download the same dat again

<img width="667" alt="screen shot 2017-01-12 at 14 45 40" src="https://cloud.githubusercontent.com/assets/10247/21892042/d07ce518-d8d5-11e6-9f2e-15d8bb889cec.png">

**Comment by yoshuawuyts** [comment]
Looks like we should be using mkdirp right?
