### ISSUE TITLE
fix duplicate file drop

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#15]

**Comment by juliangruber** [comment]
this issue is being worked on in hyperdrive: https://github.com/mafintosh/hyperdrive/issues/63

**Comment by karissa** [comment]
what is the issue here? will this be fixed by the recent changes to hyperdrive-import-files?

**Comment by juliangruber** [comment]
I'm 50/50 on this one...on one hand it would be nice to de dupe files, on the other hand, hashing everything is too expensive and simply relying on mtimes for deduping isn't safe. I'd say we should make the stack work in a way that it doesn't matter really, even if a file is added again.

**Comment by juliangruber** [comment]
@mafintosh what do you think about this one? ^

**Comment by Kriesse** [comment]
ping @mafintosh @juliangruber any update on this?

**Comment by Kriesse** [comment]
ping @juliangruber – not sure what's the status here?

**Comment by juliangruber** [comment]
this is not for dat desktop to solve, it's a hyper* issue. closing here as we haven't settled on a solution yet.
