### ISSUE TITLE
crypto_secretbox_easy error

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#153]
Not sure what's happening or if this is tracked yet, but I get this when running the app locally. Either right after starting, or when attempting to import a Dat.

![image](https://cloud.githubusercontent.com/assets/53684/22046963/f4d0aa38-dcd8-11e6-90d1-fa6dfdc3cc25.png)

**Comment by juliangruber** [comment]
I think @yoshuawuyts had this before too. Maybe try with a fresh set of dependencies, `rm -Rf node_modules && npm cache clean && npm install`.

**Comment by Kriesse** [comment]
@juliangruber tried a fresh set of deps, still seeing the same error as soon as i
either
a) import a dat
or 
b) someone else tries to connect to a dat that i created from a local folder

**Comment by karissa** [comment]
Seems like it is something to do with a bad electron rebuild, running `npm run rebuild` does not fix it.

**Comment by karissa** [comment]
doing `rm -rf ~/.electron && npm run clean && npm run rebuild && npm run bundle` seemed to work for me, will work with kriesse to get this working

**Comment by karissa** [comment]
try also:
```
npm install -g electron-recompile
electron-recompile --electron=1.4.6
```

**Comment by yoshuawuyts** [comment]
Have you tried clearing your cache? I ran into something similar until it
somehow went away

**Comment by Kriesse** [comment]
yup, tried with fresh dependencies + clear cache a few times, didn't help

**Comment by karissa** [comment]
I updated the rebuild script in package.json -- if I run `npm rebuild` directly, it seems to work.

```
npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source
```

**Comment by juliangruber** [comment]
I cleared all caches on my machine and did a fresh install but still don't get that error.

The dependency in question here is sodium-prebuilt, which lives in the tree at 

![screen shot 2017-01-19 at 11 39 49](https://cloud.githubusercontent.com/assets/10247/22103588/07a67c50-de3c-11e6-9789-2ee81b226d2a.png)

Which node version are you using? Can you try this: Upgrade to latest node, then do the same clean install procedure again.

**Comment by yoshuawuyts** [comment]
Yeah, this was the exact same error I had - and then it suddenly went away;
suspect it might indeed be cache related / requires a rebuild.

**Comment by Kriesse** [comment]
@juliangruber I'm on v6.2.2, which version should I try?

**Comment by juliangruber** [comment]
hm very strange, that should def. be new enough. do you maybe have a chance to debug this with @yoshuawuyts?

**Comment by maxogden** [comment]
@yoshuawuyts tried debugging this with @Kriesse today and got into this state after trying everything, seems to happen every time on her machine:

![screen shot 2017-01-20 at 11 30 13 am](https://cloud.githubusercontent.com/assets/39759/22162540/f5bbb208-df03-11e6-9573-0df6709206fb.png)

notice how i can `require('sodium-prebuilt')` just fine in the console, but in the bundle it fails. do you think this is related to the magic stuff you're doing with bundling node code?

**Comment by juliangruber** [comment]
@maxogden @Kriesse can you post the `bundle.js` somewhere so I can try running it locally?
