### ISSUE TITLE
Window is not draggable on welcome screen

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#159]
probably because no top bar is defined?

**Comment by yoshuawuyts** [comment]
Yeah, I think so

**Comment by yoshuawuyts** [comment]
I'm not able to reproduce it, I can drag my window around without a problem

**Comment by yoshuawuyts** [comment]
Weird, but then the latest build version I tried I suddenly can't drag it anymore. I think your instinct is right and we should restore the top bar

**Comment by karissa** [comment]
Webtorrent has a styled top bar we could borrow code from I believe, that is also draggable! Not sure how important it is though right now to have it styled as long as its draggable. Can push styling of it to a later issue!
