### ISSUE TITLE
UI for syncing metadata

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#166]
On _very large dats™_ it can take a while to sync the metadata. This happens before any chunks get downloaded, so the progress stays at 0% for a while. This is why in the CLI we show two progress bars. I was wondering if we could perhaps come up with a good way to signal this in the desktop too.

cc/ @Kriesse got any ideas for this perhaps?

---
### cli screenshot
<img width="787" alt="screen shot 2017-01-23 at 02 21 37" src="https://cloud.githubusercontent.com/assets/2467194/22188167/bcd14672-e112-11e6-8d04-4f09893bdac2.png">

**Comment by juliangruber** [comment]
What if we show the total percentage of metadata + content downloaded?

**Comment by juliangruber** [comment]
see #174

**Comment by yoshuawuyts** [comment]
Metadata syncing isn't taking too long now so it's not too much of a problem; once https://github.com/datproject/dat/issues/638 is fixed I think we can revisit this probably as it's easy to add - should take a few weeks (:

**Comment by yoshuawuyts** [comment]
I think most of this will be covered by https://github.com/datproject/dat-desktop/issues/184 - closing for now
