### ISSUE TITLE
share dialog dismisses itself

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#171]
this is the flow of events after me only opening the share dialogue:

![screen shot 2017-01-26 at 12 59 19](https://cloud.githubusercontent.com/assets/10247/22330596/56fc8b06-e3c7-11e6-80bc-0e1e53c12bbe.png)

**Comment by yoshuawuyts** [comment]
https://github.com/yoshuawuyts/base-elements/commit/8a274ca013356e6a13159385a029d495e92f6f91 might fix this

**Comment by yoshuawuyts** [comment]
let's reopen this if it keeps happening
