### ISSUE TITLE
Highlight an imported/created Dat in the list

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#180]
In longer lists, it becomes hard to find the Dat you just added, so it should be highlighted visually, e.g. with a yellow background that fades out.

**Comment by Kriesse** [comment]
Added the styles. 
To Do: Apply the class `fade-highlight` to a Dat that is added to the list.
(https://github.com/datproject/dat-desktop/commit/3d7e3f671d33383f6dbcbce60a26329d4f60103f#diff-4b7a7e325c25f4203cf9fb13f0261487R216)

**Comment by juliangruber** [comment]
@Kriesse is the class definition still there?

**Comment by juliangruber** [comment]
WIP pull request here: https://github.com/datproject/dat-desktop/pull/362
