### ISSUE TITLE
let author add/edit metadata (title, author)

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#185]
We can use in place editing for setting `.title` and `.author` in `dat.json` via the desktop app!

**Comment by yoshuawuyts** [comment]
@Kriesse assigned this to you as it'd be cool to have designs for this before working on it

**Comment by Kriesse** [comment]
Cool! In future releases, we should also have a full edit view, as inline edits come with a few accessibility issues.
Here are mockups for inline-editing, almost the same except how we handle save/cancel:

# Version A (implicit Save, explicit Cancel):
Changes are saved when the user clicks out of the editable area. 
Changes are dismissed when the "x" is clicked.

### Edit and Save:
![inline-editing_a](https://cloud.githubusercontent.com/assets/53684/23515142/9b8acad6-ff69-11e6-8867-c683364149be.gif)

### Edit and Cancel:
![inline-editing_a_cancelled](https://cloud.githubusercontent.com/assets/53684/23515146/9d878860-ff69-11e6-91d6-5009c8ff8fe9.gif)

# Version B (explicit Save, implicit Cancel):
The edits are saved when the button "Save" is clicked. 
The edits are dismissed when the user clicks outside of the editable area.

### Edit and Save:
![inline-editing-b](https://cloud.githubusercontent.com/assets/53684/23515183/b4829a96-ff69-11e6-8a74-f99286d50691.gif)

### Edit and Cancel:
![inline-editing-b_cancelled](https://cloud.githubusercontent.com/assets/53684/23515193/b8723d78-ff69-11e6-8157-973e7eb156e4.gif)

**Comment by juliangruber** [comment]
I agree with an eventual full edit screen, and for now I favor version B, as it's more explicit

**Comment by karissa** [comment]
dependent upon having a dat.json file #255

**Comment by yoshuawuyts** [comment]
We decided on the call to go for option B first, and see how well that works

**Comment by yoshuawuyts** [comment]
@Kriesse it's been merged now, could you do the styling bits? Thanks!

**Comment by Kriesse** [comment]
The behavior needs a but of fine-tuning.
- [ ] after click, show the current title in the editable field
- [ ] give an indication that it's saving and saved (see mockup)
- [ ] when clicking outside of the editable area, editing is canceled (right now only "escape" does that)

**Comment by juliangruber** [comment]
since @yoshuawuyts is out for a week I'll help with this :)

**Comment by juliangruber** [comment]
@Kriesse how shall we implement the indication for successful save?

**Comment by Kriesse** [comment]
@juliangruber " when clicking outside of the editable area, editing is canceled" does not work for me yet

**Comment by juliangruber** [comment]
@Kriesse maybe try with a fresh set of node modules? it works for me

**Comment by Kriesse** [comment]
Done! https://github.com/datproject/dat-desktop/pull/352
