### ISSUE TITLE
Importing dats from the beta.datproject.org doesn't work

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#186]
E.g. `79cf7ecc9baf627642099542b3714bbef51810da9f541eabb761029969d0161b` gets stuck at 100% / 0bytes, no error

**Comment by juliangruber** [comment]
no sources found on beta.datproject.org either https://beta.datproject.org/view/79cf7ecc9baf627642099542b3714bbef51810da9f541eabb761029969d0161b

**Comment by Kriesse** [comment]
ping @karissa

**Comment by yoshuawuyts** [comment]
seems like the cali civic data is working fine; densho and nasa seem down :(

**Comment by Kriesse** [comment]
For launch day: Can we have those example datasets on more than one server?

**Comment by Kriesse** [comment]
@clkao Can you help with this?

**Comment by karissa** [comment]
this seems like an issue with the dats currently up on the site, theyre fixed now
