### ISSUE TITLE
Run the `watch` task in process

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#187]
This way it's always keeping bundles up to date in dev, and no need to keep a second terminal open

**Comment by yoshuawuyts** [comment]
Prior art https://github.com/yoshuawuyts/playground-bankai-in-electron

**Comment by yoshuawuyts** [comment]
Some stuff I ran into:
- the output when compiling needs to be in the root dir. e.g. `./bundle.js`. Doing `./dist/bundle.js` wouldn't work.
- haven't figured out how to exclude `watchify`, `browserify` and the like (dev deps) from the production bundle - this is a hyper optimization tho, and unless we come up with something trivial not worth spending time on I reckon

**Comment by juliangruber** [comment]
We could also instead of serving bundles via http run the watch task and make it write the bundle to disk, which would be the simplest change for now, albeit less flexible

**Comment by juliangruber** [comment]
> haven't figured out how to exclude watchify, browserify and the like (dev deps) from the production bundle - this is a hyper optimization tho, and unless we come up with something trivial not worth spending time on I reckon

we could do something like, on bundle copy the app folder to a temporary folder, remove dev deps from package.json, re install deps, bundle

**Comment by yoshuawuyts** [comment]
Oh actually, we could do `npm prune --production` I think to remove all dev
deps :D - saves us a whole bunch of reinstalling - def digging this idea

**Comment by juliangruber** [comment]
PR in #189
