### ISSUE TITLE
Improve user error feedback UX: Show modal when user enters something invalid into "import dat" 

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#209]
@yoshuawuyts as discussed, let's do this:

- [x] when it is not a dat link: Show a modal "Not a Dat Link. Looks like you entered something that we can not import. Please enter a valid Dat link.'
- [ ] when it is a dat link, but is already imported: Show a modal "Already imported Dat. This Dat has already been imported. You can find it in your list of Dats."

Copy is just a starting point, let’s review together.

**Comment by Kriesse** [comment]
@yoshuawuyts How can I trigger this dialog? (Would like to review it – I guess except visual tweaks this is done?)

**Comment by yoshuawuyts** [comment]
@Kriesse In the console do:
```js
throw new Error('oops')
```
