### ISSUE TITLE
When app crashes, give user options to recover

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#213]
When app crashes, give user last resort options to clear database / delete date, but make very clear that these actions are destructive.

### Note: Rough wireframe, not final colors etc:
![image](https://cloud.githubusercontent.com/assets/53684/22839829/533e717c-efcb-11e6-8b0b-36e0b4b04e38.png)

**Comment by yoshuawuyts** [comment]
@Kriesse what's the color of the yellow background there?

**Comment by yoshuawuyts** [comment]
oh hold on, looks like `--color-yellow-disabled` http://datproject.github.io/design/ :sparkles:
