### ISSUE TITLE
if you hit 'create dat' before manager is populated it errors out

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#215]
<img width="929" alt="screen shot 2017-02-10 at 6 16 56 pm" src="https://cloud.githubusercontent.com/assets/633012/22850371/1f4d211e-efbd-11e6-9ada-cd85119676f8.png">

Lokos like the manager is created as part of some waterfall tasks but it still renders the 'create' button before the `manager` variable is populated...

**Comment by yoshuawuyts** [comment]
Fixed by https://github.com/datproject/dat-desktop/pull/217
