### ISSUE TITLE
generate brew install script

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#218]
stumbled on [pup](https://github.com/ericchiang/pup) which has a clever trick to do homebrew installs:
```sh
brew install https://raw.githubusercontent.com/EricChiang/pup/master/pup.rb
```
resolves to:
```rb
# This file was generated by release.sh
require 'formula'
class Pup < Formula
  homepage 'https://github.com/ericchiang/pup'
  version '0.4.0'

  if Hardware.is_64_bit?
    url 'https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_darwin_amd64.zip'
    sha256 'c539a697efee2f8e56614a54cb3b215338e00de1f6a7c2fa93144ab6e1db8ebe'
  else
    url 'https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_darwin_386.zip'
    sha256 '75c27caa0008a9cc639beb7506077ad9f32facbffcc4e815e999eaf9588a527e'
  end

  def install
    bin.install 'pup'
  end
end
```
Which in turn we can use for `dat-desktop`. Think this is pretty cool; perhaps we could even leverage this to bundle the `dat` command. For all those folks that for whatever reason can't pull node onto their system first

**Comment by karissa** [comment]
Hell yeah we need this for dat.. most people don't want to use npm to install.

Probably makes less sense for dat desktop cause ppl can download it as a dmg already, right?

**Comment by yoshuawuyts** [comment]
We're on brew cask now :tada: https://github.com/caskroom/homebrew-cask/pull/30288
