### ISSUE TITLE
formalize our styled components

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#219]
Noticed our buttons and a few other components weren't as flexible as they
could be. I wanted to set some custom style tags, but wasn't able to. Our
current API looks like this:
```js
html`
  ${button({
    text: 'Close',
    style: 'filled-green',
    cls: 'fr ml3',
    click: onexit
  })}
`
```

Instead I reckon it might be better if we enumerate our different type of
elements in JS, and allow passing in an object with properties directly. This
is very feasiable because `bel` knows how to expand and apply objects passed in
directly. e.g.

```js
html`
  ${button.green('Close', {
    class: 'fr ml3',
    onclick: onexit
  })}
`
```
This allows us to still apply things like the `style` property on the element,
while also being easy to remember because we're not modifying argument names.
It also means we can remove a bunch of custom syntax, making it easier to
learn if you're already familiar with the property names in HTML.

I think this approach is applicable to most of our other elements too. Thoughts?

**Comment by Kriesse** [comment]
Looks great – wasn't happy with the current solution anyway but didn't know how to improve it. This looks much more intuitive. It would be helpful for me to see a few more examples (or build them together).

**Comment by yoshuawuyts** [comment]
Woot, yeah let's do it!
