### ISSUE TITLE
Network number after disconnect does not update

### ISSUE THREAD

**Issue by joehand** [datproject/dat-desktop#227]
The `peer.once('close')` event is called before the peer count gets changed. So the number doesn't update when `update` is called on close. The count goes down [when this happens](https://github.com/mafintosh/discovery-swarm/blob/master/index.js#L338) in discovery-swarm.

```
dat.network.on('connection', function (peer) {
  update()
  peer.once('close', update) // called too early!
})
```

There may be an easy fix for this. I used intervals in the CLI as that was a bit more reliable and less jumping around with fast connections/disconnections (but max and I are working to solve that problem in discovery-swarm anyways).

**Comment by juliangruber** [comment]
this is for now fixed in dat-worker ^
