### ISSUE TITLE
"Import Dat" Input doesn't clear after adding a Dat

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#229]
After entering a Dat link and hitting enter, it looks like this:

![image](https://cloud.githubusercontent.com/assets/53684/22925449/1dfbc704-f2a9-11e6-9960-3180e4ac60f2.png)

Same after it loses focus:

![image](https://cloud.githubusercontent.com/assets/53684/22925495/419f6148-f2a9-11e6-92e0-0dd10bd8d075.png)

**Comment by karissa** [comment]
seems closed by #232
