### ISSUE TITLE
show down-/upload status

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#23]

**Comment by juliangruber** [comment]
from dat.land:

```js
function attachSpeedometer (archive) {
  var speed = speedometer(1)
  var $els = {
    speed: document.getElementById('speed'),
    upload: document.getElementById('upload-speed'),
    download: document.getElementById('download-speed')
  }
  var timer
  function update (direction, data) {
    if (!data.length) return
    var bytesPerSecond = speed(data.length)
    if (bytesPerSecond && $els[direction]) {
      $els.speed.style.display = 'block'
      $els[direction].innerHTML = direction + ' ' + prettyBytes(bytesPerSecond)
      window.clearTimeout(timer)
      timer = window.setTimeout(function () {
        $els.speed.style.display = 'none'
        $els.upload.innerHTML = ''
        $els.download.innerHTML = ''
      }, 1500)
    }
  }
  archive.on('upload', function (data) {
    update('upload', data)
  })
  archive.on('download', function (data) {
    update('download', data)
  })
}
```

**Comment by joehand** [comment]
I'm going to try to improve stats & progress in the CLI this week too (especially for live updates). Most of that will happen in dat-js but I think some of that should end up in hyperdrive too.

Right now, I'm doing this [hacky thing](https://github.com/joehand/dat-js/blob/master/index.js#L215) to show progress on resumes.

**Comment by joehand** [comment]
With hyperdrive 7.5, it seems like it'll be a lot easier to track blocks on download (instead of bytes). Going to start transitioning to that (see [this issue](https://github.com/datproject/dat/issues/526))

**Comment by Kriesse** [comment]
@joehand As https://github.com/datproject/dat/issues/526 is closed, can we get this from dat-js?

**Comment by juliangruber** [comment]
@Kriesse we can get it from hyperdrive-stats currently, yes. Do you want to add UI for this?

**Comment by Kriesse** [comment]
@juliangruber Cool, yes –  to clarify, in the UI this would be the hexagon in front of each row, right?
Here's the latest mockup:

![image](https://cloud.githubusercontent.com/assets/53684/20433906/dea8e6ce-ada5-11e6-927c-e95890d92237.png)

**Comment by juliangruber** [comment]
that as well. see https://github.com/datproject/dat-desktop/pull/84

**Comment by juliangruber** [comment]
reopening as transfer speeds are still missing

**Comment by joehand** [comment]
These are exposed in dat-node as `dat.stats.network.uploadSpeed` and  `dat.stats.network.downloadSpeed`.

I use an interval to update them, right now there is no events on stats.network. Let me know if you'd like me to add them.

**Comment by yoshuawuyts** [comment]
Closing this in favor of https://github.com/datproject/dat-desktop/issues/248 which is specifically for the missing up/down speed & "full replica" vs "partial replica" peers
