### ISSUE TITLE
the first time importing a dat.json file doesn't populate the list with metadata

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#233]
If you have a dat.json file in a folder and then create a new dat with it, the dat.json file never gets read -- it says 'anonymous' author with the truncated key in the title spot.

But if you restart the app, you'll see that it's able to read the dat.json file from the manifest and displays the expected title and author.

**Comment by juliangruber** [comment]
depends on https://github.com/datproject/multidat/pull/8

**Comment by juliangruber** [comment]
pull request here: https://github.com/datproject/dat-desktop/pull/316
