### ISSUE TITLE
utp not working in dat-desktop

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-desktop#238]
when testing with @joehand and @yoshuawuyts we found out that utp (for some reason we don't yet know) is not getting used at all in dat-desktop@master. looking into it now

**Comment by maxogden** [comment]
OK getting super weird behavior with require('utp-native')

If I change this line in 'discovery-swarm':

```
this._utp = opts.utp === false || !utp ? null : utp().on('connection', onconnection)
```

to this:

```
this._utp = utp()
this._utp.on('connection', onconnection)
```

Then Dat Desktop freezes and never loads my list of dats

**Comment by juliangruber** [comment]
After your change it also freezes on my machine. However I can manually check udp running this in the console in the same session:

```js
require('multidat/node_modules/dat-node/node_modules/hyperdiscovery/node_modules/discovery-swarm')({})
THIS._UDP undefined
```

**Comment by juliangruber** [comment]
I think I found the issue. Apparently when you child_process.fork in electron, runtime in the forked process is node, not electron. Then you get this error requiring utp-native:

```
Error: No native build was found for runtime=node abi=50 platform=darwin arch=x64
```

Working on a fix now

**Comment by mafintosh** [comment]
I released utp-native with bundled prebuilds for all platform (excluding windows) so this should be fixed by that if you reinstall. @juliangruber is the issue you describe gonna affect the other native modules also? If so I can do a release of sodium-encryption|signatures with sodium-native since that ships with bundled prebuilds as well

**Comment by juliangruber** [comment]
this seems to work for me now. please close when you ACK

**Comment by juliangruber** [comment]
(re install node_modules)

**Comment by maxogden** [comment]
woot

<img width="822" alt="screen shot 2017-02-17 at 2 14 36 pm" src="https://cloud.githubusercontent.com/assets/39759/23085238/70720ef2-f51b-11e6-8245-04edd0cd4b3d.png">
