### ISSUE TITLE
store and read meta information in dat.json

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#24]
- [x] title
- [x] author

**Comment by juliangruber** [comment]
@Kriesse can you think of a way to add the author to the ui?

**Comment by Kriesse** [comment]
@juliangruber how about this?
![image](https://cloud.githubusercontent.com/assets/53684/18349999/10545bae-75d4-11e6-9fba-38503826f539.png)

**Comment by juliangruber** [comment]
looks fantastic!

**Comment by juliangruber** [comment]
@Kriesse there's `dat.author` now in your template code, which will be read from the dat's `dat.json` as well
