### ISSUE TITLE
.dmg build instructions

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-desktop#242]
Trying to make it possible for multiple ppl to cut releases of the mac .dmg

- Is the dmg process manual, if so what are the steps?
- Does it involve xcode signing, and can we put the keys in our secrets repo?
- Are there already docs for this that I am too dense to find?

**Comment by juliangruber** [comment]
> Is the dmg process manual, if so what are the steps?

It's `npm run dist`, which is now also mentioned in the README

> Does it involve xcode signing, and can we put the keys in our secrets repo?

Yes it does. It's not hard to make it work on multiple machines though, so I'll add it to the secrets repo

**Comment by juliangruber** [comment]
However, we have travis cut releases now, fully automated. Is this still an issue then?
