### ISSUE TITLE
more dat-worker logging / debugging / error handling

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#243]

**Comment by maxogden** [comment]
background, I was testing desktop with someone on a macbook pro, they dl'd dmg from the latest release and it opened ok but importing/creating a dat has no effect in the UI and logs no errors to the console.

it was weird cause nothing in the UI happened at all, not log events or anything. but running Help > Doctor with DevTools opened passed all the doctor tests

**Comment by juliangruber** [comment]
curious, is there a chance that dat-worker works, but dat doesn't? @maxogden would it be possible to try the cli on that machine?

**Comment by juliangruber** [comment]
made two major changes to help with this:

- dat-worker now has debug() support and for now always logs its debug output (don't worry, it's just at init time, doesn't log anything more and therefore doesn't spam the console)
- made it so dat-worker child std{out,err} will be logged to the console immediately

Waiting for the build, then let's test on that machine again and watch the console

**Comment by juliangruber** [comment]
I can reproduce this bug on my local machine now - or one that looks like it - and the above didn't help. Working on it more then.

**Comment by juliangruber** [comment]
fixed, and added more logging
