### ISSUE TITLE
Warn on duplicate Dat

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#245]
When already imported Dat. This Dat has already been imported. You can find it in your list of Dats

**Comment by yoshuawuyts** [comment]
Blocked by https://github.com/datproject/multidat/issues/2 - should be reasonably easy to implement tho

**Comment by yoshuawuyts** [comment]
@juliangruber assigning you for now because it's blocked on `multidat` - do you mind picking this one up? Thanks! :grin:

**Comment by juliangruber** [comment]
https://github.com/datproject/multidrive/pull/9

**Comment by yoshuawuyts** [comment]
awesome, reviewed & looking great :sparkles:

**Comment by juliangruber** [comment]
multidrive now noops when adding an archive twice. Should we still add the check and warn here?

**Comment by juliangruber** [comment]
We decided that the warning would be helpful, so adding logic for `err.warn = true` triggering a warning dialogue

**Comment by juliangruber** [comment]
needs https://github.com/datproject/multidrive/pull/10

**Comment by juliangruber** [comment]
work started in https://github.com/datproject/dat-desktop/compare/add/warning-on-duplicate-dat?expand=1

**Comment by juliangruber** [comment]
blocked by #292

**Comment by juliangruber** [comment]
we're detecting duplicates in multidrive now, which works in the case where you clone a dat redundantly. in the case where you share one though, we currently always get the LevelDB error first, because the dat needs to be initialized before we know its key. If we do the duplicate check on the directory as well though, that wouldn't be necessary.

**Comment by juliangruber** [comment]
pull request here: https://github.com/datproject/dat-desktop/pull/295
