### ISSUE TITLE
Host our own release server

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#247]
We've noticed that GitHub releases can be rather unstable, so in order to guarantee the app can be downloaded we should probably run our own release server

**Comment by yoshuawuyts** [comment]
In the short term we can probably do a quick and dirty thing with S3 and / or Nginx. Would require manual uploading of the package but it probably works.

In the long term it'd perhaps be useful to have a dedicated service that tails a project through a webhook and caches the tarball. Doing stuff such as retrying downloads until it has it. This can then in turn be cached again by a CDN / Nginx.

**Comment by yoshuawuyts** [comment]
cc/ @juliangruber

**Comment by juliangruber** [comment]
> Would require manual uploading of the package but it probably works.

We can use the github releases api still though, and simply run a CDN on top

**Comment by juliangruber** [comment]
The simplest solution I see right now is to manually upload releases to a public S3 bucket and use the public S3 links on the website.

**Comment by juliangruber** [comment]
A more cost efficient alternative might be to upload to our own servers and run a simple http file server like https://github.com/tj/serve

```bash
$ serve releases/
```

**Comment by yoshuawuyts** [comment]
Interestingly enough we haven't heard any feedback of users that they couldn't download it. Also looks like we had ~200 downloads in the past few days. This might perhaps not be as critical as we thought?

**Comment by juliangruber** [comment]
I'm fine with marking this priority low and then either when there are complaints work on it again or drop it

**Comment by yoshuawuyts** [comment]
yeah cool - doing that; moving out of milestone too then to mark it's resolved for now

**Comment by yoshuawuyts** [comment]
haven't heard of any problems with hosting releases - safe to close
