### ISSUE TITLE
Show more network stats in the UI

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#248]
When downloading a dat, it is often useful to know things about the network. Currently we're tracking the peer count, but it'd also be good if we:
- [x] track upload / download speeds
~~- track "peers that have the full dataset" vs "peers that have a partial replica"~~

Labeling this as high priority because not having any information about the state of the network can be frustrating for users as they've got no idea what's causing slowness or even halted downloads.

---
@Kriesse any ideas on a UI for this?

**Comment by yoshuawuyts** [comment]
As per https://github.com/datproject/dat-desktop/issues/23#issuecomment-280853931 we can implement these through `dat.stats.network.uploadSpeed` and  `dat.stats.network.downloadSpeed`. There are no events so currently they're updated using a loop

**Comment by Kriesse** [comment]
@yoshuawuyts Updated mockup. Please review, does that make sense? 
![image](https://cloud.githubusercontent.com/assets/53684/23162914/9354683a-f830-11e6-8524-19c3ba8bfbde.png)

Related, as it also helps to the user to understand what the status is of each Dat: https://github.com/datproject/dat-desktop/issues/184

Do we need stats on peers with partial/full datasets yet? In favor of keeping the overview uncluttered,  suggest to have this part of a potential future feature: extended stats (e.g. in a panel on the bottom, think utorrent).

**Comment by karissa** [comment]
Yeah, I like it! 

Let's chat about a desktop roadmap for the next milestone with @maxogden, it'd be good to get a sense of what would be the most exciting to show off in a demo. It could be easy to rewrite github.com/mafintosh/dat-drop here in a panel when you click a dat.

**Comment by karissa** [comment]
And yes, peer partial replication stats should be a separate issue.

**Comment by yoshuawuyts** [comment]
@Kriesse neat, yeah that makes a lot of sense! Digging it.

And yeah sounds good; created a separate issue for the detail view https://github.com/datproject/dat-desktop/issues/260

**Comment by yoshuawuyts** [comment]
@karissa gonna check it out - hadn't seen that yet :sparkles:

**Comment by juliangruber** [comment]
getting started with this now

**Comment by juliangruber** [comment]
started my work here: https://github.com/datproject/dat-desktop/pull/268

**Comment by Kriesse** [comment]
@juliangruber Oh perfect thanks for preparing that! Will take it from here and start with styling.

**Comment by Kriesse** [comment]
@juliangruber styling done for now! i'll assign to you, let me know if i missed anything.

**Comment by juliangruber** [comment]
merged!
