### ISSUE TITLE
Investigate UI element caching

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#250]
As per https://github.com/datproject/dat-desktop/issues/152, the app sometimes spins when lots of updates happen (e.g. network events). We should probably investigate caching elements.

- [ ] cache list items by assigning them unique IDs (`morphdom` specific)
- [ ] cache individual elements by using `nanocomponent` (depends on https://github.com/yoshuawuyts/nanocomponent/issues/11)

**Comment by juliangruber** [comment]
Is this still an issue? We're getting way less updates with dat-worker now

**Comment by juliangruber** [comment]
(it doesn't seem to me)

**Comment by yoshuawuyts** [comment]
We fixed a lot of the perf issues here; moving to priority medium. Gonna build a component system first and move to less files before digging into this again.

**Comment by yoshuawuyts** [comment]
I think we can close this; we don't have any pressing perf issues right now and I'm sure there's always room to improve. New choo should make it v. easy to debug perf also, sooooo closing :sparkles:
