### ISSUE TITLE
make window movable while app boots

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#253]
you can't drag the app around while it's in this initial state:

![screen shot 2017-02-21 at 10 39 24](https://cloud.githubusercontent.com/assets/10247/23159164/07f47a5e-f822-11e6-8f7d-433654a86cc8.png)

**Comment by Kriesse** [comment]
Same applies for window in "unexpected issue" state.

**Comment by Kriesse** [comment]
This has be fixed for the intro screen by applying `-webkit-app-region: drag;`
(However the window will only became draggable after restarting the app, refreshing doesn't help)
