### ISSUE TITLE
dat(1) automatically creates dat.json, dat-desktop doesn't

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#255]

**Comment by yoshuawuyts** [comment]
If we always expect a `dat.json` to exist in new dats, should it perhaps be part of `dat-node`? Or don't we necessarily expect that to be the case? cc/ @joehand

**Comment by juliangruber** [comment]
^ exactly what i was thinking

**Comment by joehand** [comment]
Yep, it should be part of dat-node. Ran out of time before releasing CLI and just put it in CLI code. 

https://github.com/datproject/dat-node/issues/54

**Comment by juliangruber** [comment]
awesome, leaving this issue open as a remainder that this functionality will float in with a future dat-node update :)

**Comment by karissa** [comment]
Started it here https://github.com/datproject/dat-node/pull/122

**Comment by joehand** [comment]
Made a [dat-json](https://github.com/joehand/dat-json) module so we can start integrating. I can put this into dat-node directly as well.

**Comment by yoshuawuyts** [comment]
Neato!

**Comment by juliangruber** [comment]
it now does :)
