### ISSUE TITLE
Popup doesn't go away

### ISSUE THREAD

**Issue by piccoloaiutante** [datproject/dat-desktop#259]
I think i found a bug and these are the step that consistently gave me the same outcome:

- insert open.whitehouse.gov link to download dataset: 6fa91405f280c30cedd461dfcd3b4fffffb27759e26f8135b7cbdfe08870ccb2.
- start download
- then cancel it pressing 'yes, remove dat'.
![screen shot 2017-02-21 at 16 54 41](https://cloud.githubusercontent.com/assets/867842/23172788/401755c0-f857-11e6-964f-804b43164a5a.png)

- while download is still there click again on bin to cancel download.
- press again 'yes, remove dat' button.
- an error popup appears and even if you click on 'ok' puppy will stay there.
![screen shot 2017-02-21 at 16 53 58](https://cloud.githubusercontent.com/assets/867842/23172799/4775e46c-f857-11e6-8cf0-804de8e0cd97.png)

Let me know if you aren't able to reproduce :)

**Comment by yoshuawuyts** [comment]
Hey there 👋, thanks for reporting! Quick question:

> while download is still there click again on bin to cancel download

By this, do you mean that the element _eventually_ is removed, but not immediately - and if you click it it creates an error?

**Comment by piccoloaiutante** [comment]
yes @yoshuawuyts , because of the time taken to remove the user can click again and create this condition.

**Comment by yoshuawuyts** [comment]
@piccoloaiutante great, I think I know how to solve it then. Thanks heaps for reporting!

**Comment by juliangruber** [comment]
@yoshuawuyts fixed the modal dismissal in https://github.com/datproject/dat-desktop/pull/295/commits/b08cff0665fd0a6736faf304636a8aff4fbc92a9

**Comment by juliangruber** [comment]
fixed in master now
