### ISSUE TITLE
newsletter

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#264]
@Kriesse:

> @karissa Love the description!
For the newsletter: I don't think the blogpost works well as a newsletter. Would like to design a simple template for this – do we have a Mailchimp (or similar) account I can use?

@karissa:

> OK @Kriesse ,-- We have a tinyletter account, does that work? Or do you need something closer to mailchimp? I'll give you the creds.

**Comment by yoshuawuyts** [comment]
cc/ @karissa are you usually responsible for the newsletter going out? Few questions:

- when does the newsletter usually go out?
- what kind of content are we looking for? I've found https://tinyletter.com/datdata but it doesn't have an archive, so not sure what's usually the case
- is there any content we need to provide? (for desktop, but also in general I guess)
- is this the right place to discuss newsletter things? Do we have a tracking repo?

Thanks!

**Comment by yoshuawuyts** [comment]
Also as a more general question: it says this is "in progress" - @juliangruber do you know who's working on this?

**Comment by juliangruber** [comment]
> Also as a more general question: it says this is "in progress" - @juliangruber do you know who's working on this?

it read to me like @Kriesse and @karissa were working on this

**Comment by Kriesse** [comment]
Doesn't seem actionable at the moment or directly related to Dat-Desktop. Closing.
