### ISSUE TITLE
climate use case

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#265]
> ping @maxogden – what was the last point in the checklist ("climate use case") about again? Is that done?

> @maxogden The climate dataset is the NASA one? It's still not working for me when I try to download it with Dat Desktop.

**Comment by yoshuawuyts** [comment]
@juliangruber could you perhaps shed some light on what needs to be done to tick off this issue? Does this mean that we can tick this off once the NASA dataset can be downloaded? Thanks!

**Comment by yoshuawuyts** [comment]
@juliangruber also just assigned you as I think "in progress" means you're working on it. If someone else is working on it please assign them instead. Thank youuuu

**Comment by juliangruber** [comment]
assigned @maxogden who iiuc is working on this

**Comment by Kriesse** [comment]
Not relevant anymore
