### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by mojoaxel** [datproject/dat-desktop#267]
I hope you guys don't mind me opening an issue to track the status of the linux build.
The build works for on ubuntu 16.04 64x with node v7.3.0.

I needed to install some dependencies for the `dist` build:

```
sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
```

I guess what is missing now is the packing e.g. as `.deb` package.

**Comment by juliangruber** [comment]
oh wow! I never tested this on Linux, great to know it _just works_ :)

If all we need to add is the proper build process, that might land pretty soon I'd say

**Comment by yoshuawuyts** [comment]
@mojoaxel woot, thanks for opening this issue - we def appreciate it :sparkles:. I think one of the hard things for us right now is that nobody on Dat is running Linux as their main desktop OS, so testing and fixing bugs is a bit trickier.

I think a good first step might perhaps be to do a "preview" release, where we create the `.deb` packages but kinda mark it as "not really tested, might be unstable". @juliangruber does that sound alright?

**Comment by juliangruber** [comment]
@yoshuawuyts after a bit of reading, the `.AppImage` we had from CI builds actually is something that can be installed on most distributions, see http://appimage.org/. @mojoaxel would you mind giving this a try? https://github.com/datproject/dat-desktop/releases/download/untagged-ec34eac2fca159729a41/dat-desktop-1.0.3-x86_64.AppImage

I'm setting up an Ubuntu VM also so I can work on bugs there.

**Comment by yoshuawuyts** [comment]
Ohey, that's cool. Nice.

**Comment by juliangruber** [comment]
uploading it somewhere else as that url seems to be private

**Comment by juliangruber** [comment]
https://cldup.com/inWFfU9TLV.AppImage

**Comment by juliangruber** [comment]
<img width="1496" alt="screen shot 2017-02-23 at 13 18 57" src="https://cloud.githubusercontent.com/assets/10247/23258892/a9b1a624-f9ca-11e6-86fb-e28276ff4b35.png">

meh but not bad either!

**Comment by mojoaxel** [comment]
> @mojoaxel would you mind giving this a try?

@juliangruber I got the same package-version error with your version. I just pulled and build again. Now I have a wonderful running AppImage for Linux.

So Thanks to [AppImage](/probonopd/AppImageKit) I see now reason why this should not be published :tada:

**Comment by mojoaxel** [comment]
Oh, I see there is already a [linux release](/datproject/dat-desktop/releases/tag/1.0.3-pre). Great job guys!!
