### ISSUE TITLE
Linux: package .deb as well

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#269]
.AppImage has UX implications, because you need to explicitly mark it executable first. People that have never used .AppImage files before might find it easier to use .deb and .rpm etc packages.

**Comment by probonopd** [comment]
Much easier than to fiddle around with repositories and ppas:

![Make executable](https://cdn-standard4.discourse.org/uploads/appimage/optimized/1X/a4889c5cb8711d6845b58135080787d2f370af35_1_500x500.gif)

**Comment by juliangruber** [comment]
Yeah I agree, but does everyone you you just need to make it executable?

**Comment by probonopd** [comment]
I'd say, just link to the animted GIF above :-)

**Comment by juliangruber** [comment]
agreed, no need for .deb :)
