### ISSUE TITLE
"Warning: Possible EventEmitter memory leak detected"

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#270]
Seeing this when running the app locally:

![image](https://cloud.githubusercontent.com/assets/53684/23263367/546ab0de-f9de-11e6-8d6c-8fdc27229b4b.png)

App looks dead:
![image](https://cloud.githubusercontent.com/assets/53684/23263394/65db5f08-f9de-11e6-86a4-62ac67866710.png)

**Comment by juliangruber** [comment]
the "app looks dead is unrelated, we yet have to figure this out :/"

**Comment by juliangruber** [comment]
fixed the warning, let's open a new issue if the app freezes again

**Comment by yoshuawuyts** [comment]
Awesome, thanks!
