### ISSUE TITLE
Bug: Open folder on linux

### ISSUE THREAD

**Issue by mojoaxel** [datproject/dat-desktop#273]
I'm testing the latest version (5726a8ec7a3f35a83c48ed787d40b577cc968f32).
There is a problem on linux when i try to open the dats folder by clicking on the folder-icon.

It looks like the xdg-open script can not be executed in the electron context. I have no idea at the moment, because it works i the development build.

![image](https://cloud.githubusercontent.com/assets/600565/23276602/3ac7fea2-fa0b-11e6-96c7-5d36c2151c32.png)

_Also the Styles (overflow) of the error-popup should be maybe improved :wink:_

**Comment by mojoaxel** [comment]
I'll provide a fix shortly...

**Comment by yoshuawuyts** [comment]
@mojoaxel thanks for reporting! I created a separate issue for the text overflowing :sparkles:
