### ISSUE TITLE
Modal text can overflow

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#276]
As per https://github.com/datproject/dat-desktop/issues/273, when an error occurs the text in the modal can overflow. We should probably have `overflow-x: auto` or something similar.

![3ac7fea2-fa0b-11e6-96c7-5d36c2151c32](https://cloud.githubusercontent.com/assets/2467194/23359293/e5cde7b2-fce5-11e6-9f0b-d2da07584aaf.png)

**Comment by karissa** [comment]
If we make it a textarea people can easily copy and paste it to us
