### ISSUE TITLE
linux travis builds failing

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#278]
This line eg should print detected electron versions: https://travis-ci.org/datproject/dat-desktop/jobs/205778457#L210

**Comment by juliangruber** [comment]
better: deactivate for now until this is fixed

**Comment by juliangruber** [comment]
inside the travis vm, this actually happens:

```bash
travis@6d4756e39f9c:~/dat-desktop$ ./node_modules/.bin/electron --version
travis@6d4756e39f9c:~/dat-desktop$
```

**Comment by juliangruber** [comment]
fixed by https://github.com/datproject/dat-desktop/pull/303, linux builds are back!

**Comment by karissa** [comment]
woot!

**Comment by karissa** [comment]
can we close this then?

**Comment by juliangruber** [comment]
yuss!
