### ISSUE TITLE
Refactor component systems

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#280]
In preparation for https://github.com/datproject/dat-desktop/issues/250 we should probably move onto a slightly redesigned component system. This ties into https://github.com/datproject/dat-desktop/issues/219

### todos
- [x] buttons
- [x] icons
- [x] assets dir
- [x] single modal
- [x] with unit tests as we go

**Comment by karissa** [comment]
What kind of redesigns? Curious if we have some criteria we can orient around.

**Comment by yoshuawuyts** [comment]
@karissa outlined in https://github.com/datproject/dat-desktop/issues/219, discussed this with @Kriesse on Friday / iterated a little and started implementing it

**Comment by yoshuawuyts** [comment]
done!
