### ISSUE TITLE
Change Data Directory Location For Downloads

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-desktop#283]
When downloading using the Desktop client it would be nice to be able to specify where on disk the data should get stored, rather than storing it only in `~/Downloads/dat`. This would let people who want to seed data from external hard drives etc use the app.

Implementation wise, this could be done as a either a global config that can maybe be edited via JSON (easier, no UI change) or a 'Choose save location' dialog at import time (requires new UI).

---
### Todo
- [ ] store downloads location in configuration
- [ ] design UI to modify downloads location (configuration page?)

**Comment by karissa** [comment]
We might be able to implement the 'Choose save location' using the electron choose folder dialog.

**Comment by karissa** [comment]
uTorrent configuration pane: ![](http://img.snaphow.com/wp-content/uploads/images/choose-utorrent-directories-dropbox.png)

**Comment by karissa** [comment]
Hey all, this is a pretty crucial feature that is preventing users from using the app. Can we prioritize it?

**Comment by juliangruber** [comment]
Oh, then it should be prioritised of course. For understanding, can you explain why this is preventing users from using the app?

**Comment by karissa** [comment]
- People who want to use external hard drives (mentioned above)
- people who don't want their data in the downloads directory 

We've heard this feedback directly from users

**Comment by juliangruber** [comment]
you now can set the directory for each dat. shall we close this or do we want to add a pref pane as well?

**Comment by yoshuawuyts** [comment]
Think we can close it (:
