### ISSUE TITLE
Bug: Moving folder after download causes crash on restart

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-desktop#284]
A user moved their dataset out of `Downloads/dat` and then on restart got this:

```
(dmkanter) the cli seems to be working fine and sharing.  now however when I load the electron client it exits due to a crash, and asks me if I want to clear the db and exit, or delete all data and exit. I'm on version 1.0.2 of electron client, not latest (because for some reason couldn't execute installer for 1.0.3)
```

**Comment by juliangruber** [comment]
I've seen this locally as well!

**Comment by juliangruber** [comment]
The exact error is...

<img width="872" alt="screen shot 2017-03-08 at 19 20 47" src="https://cloud.githubusercontent.com/assets/10247/23717492/5e5e17d8-0434-11e7-8c6c-255a92a991c7.png">

..., a LevelDB initialization error

**Comment by juliangruber** [comment]
what should we do in this case? Start downloading again or remove from list? I'd say start downloading again.

@Kriesse what do you say?

**Comment by karissa** [comment]
If we force people to choose a download location this problem is less likely to come up -- right now if anyone wants to download something they're probably going to end up moving the files somewhere else if they don't want it in downloads/dat.

**Comment by karissa** [comment]
What about creating a "missing" or "error" state for any error that comes up for an individual dat? It could be a darker grey with a warning icon on the left. That way any future unforaweable problems with an individual dat don't crash the entire app

**Comment by juliangruber** [comment]
@karissa that is also what WebTorrent does:

![screen shot 2017-03-09 at 12 44 11](https://cloud.githubusercontent.com/assets/10247/23748962/217eadd6-04c6-11e7-9112-6f303d35f750.png)

**Comment by juliangruber** [comment]
we're properly catching this error now (not an improvement for the user yet):

![screen shot 2017-03-09 at 13 24 18](https://cloud.githubusercontent.com/assets/10247/23750133/cccdc1b8-04cb-11e7-8499-d4dba216bc82.png)

**Comment by karissa** [comment]
Sounds good @juliangruber, let's borrow the idea from webtorrent. Might be easiest to implement, too

**Comment by juliangruber** [comment]
the next step here is to change multidrive / multidat so that an error creating a dat doesn't cause the whole initialization step to error - only the one archive should have an error attached

**Comment by karissa** [comment]
Right

**Comment by juliangruber** [comment]
pull request here: https://github.com/datproject/dat-desktop/pull/302
