### ISSUE TITLE
Import Dat Flow 

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#290]
This was brought up by user feedback. When importing a new `dat` we should be able to select which files to download.

In other download clients this is usually done through a dialog that asks some details, with a default location & all files being downloaded by default.

Related: https://github.com/datproject/dat-desktop/issues/335

**Comment by Kriesse** [comment]
@yoshuawuyts Cool, good feedback. I'll work on it!

If you had any concrete clients in mind that solve this well, which ones are those?
If not I'll start with that research.

**Comment by karissa** [comment]
uTorrent does this

**Comment by karissa** [comment]
Great job documenting!  I agree that it is a pretty crucial feature

**Comment by Kriesse** [comment]
As per discussion with @yoshuawuyts, we're splitting off a separate issue for selecting download location: https://github.com/datproject/dat-desktop/issues/335

**Comment by Kriesse** [comment]
This will be a multi-step flow:

0) Click "Import Dat" button
1) Paste Dat Link 
( we now start looking for metadata)
2) select download location

optional if metadata is available:
3) give a name to the dat (if you're the owner)
4) select which files to download

**Comment by karissa** [comment]
@mafintosh and @joehand made something that is similar to the selecting which files to download https://github.com/mafintosh/directory-index-html

What's the status on this?

**Comment by yoshuawuyts** [comment]
@karissa we have some sketches on paper; think we discussed that @Kriesse is going to sketch them out next week ish, and I'll implement them after I'm back from Italy. This relies on SLEEP to land though.

**Comment by Kriesse** [comment]
Paper sketch:
![fullsizerender](https://cloud.githubusercontent.com/assets/53684/25855555/cd803af4-34d3-11e7-9d0b-4128c4168979.jpg)

**Comment by Kriesse** [comment]
@juliangruber as discussed:
![fullsizerender](https://cloud.githubusercontent.com/assets/53684/26063761/3a9471d6-398f-11e7-9097-fa47a13f5c4a.jpg)

**Comment by juliangruber** [comment]
progress:

![screen shot 2017-05-15 at 20 22 13](https://cloud.githubusercontent.com/assets/10247/26072648/8767c554-39ac-11e7-98a8-7a1314cf1ea5.png)

**Comment by Kriesse** [comment]
Mockups, also covering #260:

## Download Dat View

![dat download view](https://cloud.githubusercontent.com/assets/53684/26200007/916ac6a6-3bcc-11e7-9ab2-87a20d33726c.png)

## Detail Dat View (#260)

![dat detail view](https://cloud.githubusercontent.com/assets/53684/26200011/9382b3cc-3bcc-11e7-9ae7-d15726c4e4ec.png)

**Comment by Kriesse** [comment]
@juliangruber Updated mockups above. I started the styling in `add/download-screen`
Can you help to finish?
- [ ] debug: when entering a dat link, the download view flashes, then disappears. entering the link again fixes this.
- [ ] debug: the "fetching" state never shows up
- [ ] merge this with your work on the file list

**Comment by juliangruber** [comment]
> debug: when entering a dat link, the download view flashes, then disappears. entering the link again fixes this.

by "disappears" do you mean you get back to the dats list or that there is a blank view?

**Comment by Kriesse** [comment]
@juliangruber I think this is almost there, except the flash of empty page when importing a dat. This is what I currently  see:

1. Enter dat link
(2. Only sometimes: download view flashes for a moment)
3. Dark empty screen
4. Download view says "N/A" in metadata fields
5. Download view shows actual metadata

This is what it should be:

1. Enter dat link
2. Download view in "Fetching Metadata" state
3. Download view with actual metadata loaded

**Comment by juliangruber** [comment]
ok, yeah then you see the same as I do. Should be fixed later today!

**Comment by karissa** [comment]
nice!!

**Comment by juliangruber** [comment]
not fixed yet, but @yoshuawuyts and me are working on it!

**Comment by juliangruber** [comment]
this has landed :)
