### ISSUE TITLE
add warning modal element

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#292]
required for https://github.com/datproject/dat-desktop/issues/245.

@yoshuawuyts how are we going to do this?

**Comment by yoshuawuyts** [comment]
After https://github.com/datproject/dat-desktop/pull/285 we should have a `modal.js` file - can take the same approach as with `buttons.js` where we'd call something like `modal.warning()`

**Comment by juliangruber** [comment]
sgtm!

**Comment by yoshuawuyts** [comment]
Building choo v5 side tracked me a whole bunch - I should spend some time
on this tho; feel free to take over if it's blocking you right now

**Comment by juliangruber** [comment]
part of https://github.com/datproject/dat-desktop/pull/295

**Comment by yoshuawuyts** [comment]
Closed as per ^
