### ISSUE TITLE
pausing a dat doesn't stop uploading

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#293]
Verified this on https://github.com/datproject/dat-desktop/pull/291 that hitting pause on a dat doesn't stop it from being uploaded over MDNS - might also be the case on TCP, UDP. Def worth looking into.

**Comment by juliangruber** [comment]
@joehand hey, is this something we can solve in dat-node?

Otherwise, we could also just `.kill()` the dat-worker child processes for a clean _pause_, however that is not as efficient

**Comment by joehand** [comment]
> @joehand hey, is this something we can solve in dat-node?

Yes! I added the pause/resume (which does the same as join/leave). But I think there may have a bug in the join/leave. 

I will release a new dat-node version today that we can test.

**Comment by joehand** [comment]
This appears fixed with the upgrade to dat-node 1.4!

**Comment by juliangruber** [comment]
@joehand thank you, that fixed the MDNS case for sure! Since the others weren't reported as particular problems (yet), closing for now
