### ISSUE TITLE
add modal keyboard shortcuts

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#309]
Currently when you try to positively dismiss a modal via pressing the enter key, something strange happens: Since the focus still is on the element you clicked then triggering the modal, another modal of the same kind is created and overlayed.

The solution I think is to set the focus on the modal's positive button.

**Comment by yoshuawuyts** [comment]
haha oh wow - good point

**Comment by juliangruber** [comment]
pull request here: https://github.com/datproject/dat-desktop/pull/312
