### ISSUE TITLE
test:integration fails on travis

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#310]
See for example https://travis-ci.org/datproject/dat-desktop/jobs/212894584

Since they're passing locally (they do for me), this might best be investigated running the travis environment on your machine via docker and seeing what's going on. See https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image for a manual.

I removed the `test:integration` target from `test` for now, so our builds work again.

**Comment by yoshuawuyts** [comment]
Yeah sounds reasonable

**Comment by juliangruber** [comment]
@karissa do you have any ideas here?

**Comment by karissa** [comment]
Heyo,
Figuring out how to re enable our integration tests and writing new ones will be important to reduce chance of regressions.. it's unclear how Travis is failing us here.

**Comment by juliangruber** [comment]
my guess is because the window is created in a virtual frame buffer...I've noticed the integration tests failing locally when you switch to other windows while they're running

**Comment by juliangruber** [comment]
WIP pull request here: https://github.com/datproject/dat-desktop/pull/344

**Comment by karissa** [comment]
nice!
