### ISSUE TITLE
[QA]  v1.1.0

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#311]
In order to verify `dat-desktop@1.1.0`  works as expected.

---
#### crash reporting
- [ ] make sure error logs come through (@yoshuawuyts)

#### downloading/installation
- [x] verify http://datproject.org/ has instructions to download the correct latest release
- [x] verify the nice 'disk image' designed background comes up when you open the .dmg
- [x] verify you can drag to applications folder and double click the app to open first try (no right click open)

#### onboarding
- [x] welcome screen should show every time you open the app as long as you have no dats
- [x] make sure you can minimize, full screen, resize, and move the window
- [x] after clicking away welcome screen you should see an empty list with import dat and create new dat

#### importing and creating dats
- [x] click *create new dat* and share a local folder, you should see a new item in the list
- [x] click *import dat* and see if starts to download dat://f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062
- [x] the *progress bar* should correctly show how much progress you have downloaded
- [x] check that *network* (number of peers) is correct 
- [x] restart the app and check everything is still in place

#### working with dats
- [x] click the *link icon* and it should show a modal and copy the dat link to your clipboard on button click
- [x] click the *open in finder icon* and it should open the folder in Finder.app
- [x] click the *delete icon* and it should pop up a confirmation dialog to remove it
- [x] click the *cancel* button on the delete dialog and check if it cancels the dialog
- [x] click the *pause* button and verify all network activity halts
- [x] click the *resume* button and verify it is resumed completely

#### advanced use cases
- [x] share a dat using Dat CLI and try to import it into the desktop
- [x] create new dat in desktop and clone it using Dat CLI
- [ ] share dat on another machine using Dat Desktop and import it to your local desktop app
- [ ] create new dat in local Dat Desktop and import it on Dat Desktop running on a remote machine

#### app progress indicator
- [x] there is no progress indicator by default
- [x] while downloading dats, their cummulative progress set the app's progress indicator
- [x] having paused and unfinished dats in the list doesn't keep the progress indicator active
- [x] once all downloads finished, the progress indicator is cleared again

**Comment by Kriesse** [comment]
After installing, I tried to open the app, and am stuck at an empty view: 

![image](https://cloud.githubusercontent.com/assets/53684/24138095/263b1774-0e17-11e7-803f-1a1d42dcf156.png)

**Comment by juliangruber** [comment]
https://github.com/datproject/dat-desktop/commit/e1c7ea9047ae45c1ca5da559843a3a9d2f45339c, building again

**Comment by juliangruber** [comment]
I added new items to this list as commits since the last release demanded me to

**Comment by juliangruber** [comment]
next bug found: doesn't download the test dat (dat://f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062), cli works

**Comment by Kriesse** [comment]
ok, no i can go beyond the empty screen, but i get this: 
![image](https://cloud.githubusercontent.com/assets/53684/24139604/fe9f0ea4-0e1c-11e7-8ee5-1068a7ff485a.png)

**Comment by juliangruber** [comment]
@Kriesse that is the bug where `~/Downloads/dat/` has been removed, which we haven't fixed in this release. However, it should offer you to clear the db in this case, right? Because otherwise there's nothing you can do unless manually going to the terminal.

**Comment by Kriesse** [comment]
@juliangruber Yup! Is that something we can do now, or should we move it into the next release (or a patch?)

**Comment by juliangruber** [comment]
I'll take a look after some work on dat-worker, let's skip this one for now

**Comment by juliangruber** [comment]
fixed the downloading bug :)

**Comment by juliangruber** [comment]
I also fixed the multidat bug, we weren't cleaning up properly when you quit the app. In case it doesn't work when you next launch it, you need to clean up once manually by either restarting your machine or quitting all dat-worker processes

**Comment by juliangruber** [comment]
the link modal is a bit broken:

<img width="441" alt="screen shot 2017-03-21 at 12 57 22" src="https://cloud.githubusercontent.com/assets/10247/24146425/fad65700-0e35-11e7-9e63-60487675a3bd.png">

**Comment by juliangruber** [comment]
the peer number is incorrect, should be 0:

<img width="791" alt="screen shot 2017-03-21 at 13 00 08" src="https://cloud.githubusercontent.com/assets/10247/24146517/5ad64da4-0e36-11e7-92b5-61fe5f1e4bf3.png">

**Comment by juliangruber** [comment]
there is also a bug with the progress bar where it shows 0% although all dats have been downloaded completely

**Comment by juliangruber** [comment]
Status update:

- the copy modal style needs to be fixed
- need to test if the network works with someone else's help

**Comment by Kriesse** [comment]
Update: Modal style is fixed!
![image](https://cloud.githubusercontent.com/assets/53684/24191139/1805b568-0eeb-11e7-82fe-0125e579face.png)

**Comment by juliangruber** [comment]
1.1.0 is out! 🍾 Thank you everyone! ❤️

**Comment by Kriesse** [comment]
🎉
