### ISSUE TITLE
Bug: Update notices spawn indefinitely

### ISSUE THREAD

**Issue by waldoj** [datproject/dat-desktop#317]
Without intervention, it appears that update notices will continue to pop up, indefinitely:

![dat](https://cloud.githubusercontent.com/assets/656758/24212055/650ef8c4-0f04-11e7-8ff5-80862f8d2b5f.jpg)
The text is, for the benefit of future searching:
> Dat Desktop 1.1.0 has been downloaded and is ready to use! Would you like to install it and relaunch Dat Desktop now? [Dismiss] [Install and Relaunch]

**Comment by karissa** [comment]
Thanks @waldoj !
