### ISSUE TITLE
choo event name convention

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#318]
conversation started in https://github.com/datproject/dat-desktop/pull/315#pullrequestreview-28411454:

@yoshuawuyts 

> ohhh, we should probably decide on how to name events; in choo we usually delimit using : and camelcase for words. In the dat API we use whitespace to space words, and don't think we have namespaces. I feel we should like agree on something and then stick to it. Perhaps : to namespace and whitespace to split words?

@yoshuawuyts 

> This is not a blocker btw, perhaps something to discuss either over text or face? feel we can figure it out in 5mins when talking haha

@karissa 

> +1 on having a convention

**Comment by yoshuawuyts** [comment]
Let's chat about this on our next skype call

**Comment by juliangruber** [comment]
@yoshuawuyts and me talked about it over hangout and settled on the convention we had before:

```
<namespace>:<hyphen-separated-event-name>
```

Namespaces, because they give structure and enable more tooling. Hyphen separated event names, because that's what node core and electron use.
