### ISSUE TITLE
migrate to SLEEP marketing

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#323]
### communication
- [ ] create a blog post to explain why the migration happens
- [ ] update the docs for SLEEP
- [ ] possibly video
- [ ] tweets and stuff

**Comment by yoshuawuyts** [comment]
@juliangruber you said you wanted to take this on - any progress so far?

**Comment by juliangruber** [comment]
I have a branch here: https://github.com/datproject/dat-desktop/compare/sleep?expand=1

but there's a lot of values on `dat` missing still. i'll report back here!

**Comment by juliangruber** [comment]
wip pull request here: https://github.com/datproject/dat-desktop/pull/333

**Comment by juliangruber** [comment]
currently waiting for the stats stuff while making sure all the rest works

**Comment by yoshuawuyts** [comment]
Nice! I believe @mafintosh said he'd be working on stats on the plane over
to Portland. If so, it means we should be good to go soon ✨

**Comment by joehand** [comment]
Dat-node has these stats right now: 

```js
var stats = dat.trackStats()

// Archive stats
stats.get() // {filesTotal, bytesTotal, blocksTotal} 

// Network stats
stats.network // {uploadSpeed, downloadSpeed}

// Peer Stats
stats.peers // {total, complete}
```

Notes on current stats:

* `filesTotal` + `bytesTotal` includes duplicates counts from history. 
*  `stats.network.uploadSpeed` seems to be buggy based on adding it to CLI yesterday
* `stats.peers.complete` also seems buggy from yesterday experience

Things we need:

* Current state of archive (e.g. latest file count and byte length, not counting duplicates in history). I'll talk to Mathias about this.
* Fix those bugs

**Comment by juliangruber** [comment]
@joehand thanks for the summary! That's exactly what we need here too :)

**Comment by Kriesse** [comment]
@juliangruber Can we chat about the blog post and other marketing? Happy to help with it but need technical background first :)

**Comment by juliangruber** [comment]
closing in favor of https://github.com/datproject/datproject.org/issues/545
