### ISSUE TITLE
[QA] v1.1.2

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#324]
In order to verify `dat-desktop@1.1.2`  works as expected.

---
#### downloading/installation
- [ ] verify http://datproject.org/ has instructions to download the correct latest release
- [x] verify the nice 'disk image' designed background comes up when you open the .dmg
- [x] verify you can drag to applications folder and double click the app to open first try (no right click open)

#### onboarding
- [x] welcome screen should show every time you open the app as long as you have no dats
- [x] make sure you can minimize, full screen, resize, and move the window
- [x] after clicking away welcome screen you should see an empty list with import dat and create new dat

#### importing and creating dats
- [x] click *create new dat* and share a local folder, you should see a new item in the list
- [x] click *import dat* and see if starts to download dat://f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062
- [x] the *progress bar* should correctly show how much progress you have downloaded
- [x] check that *network* (number of peers) is correct 
- [x] check that *title* is `Densho Names Registry`
- [x] check that *author* is `Densho Digital Repository`
- [x] restart the app and check everything is still in place

#### working with dats
- [x] click the *link icon* and it should show a modal and copy the dat link to your clipboard on button click
- [x] click the *open in finder icon* and it should open the folder in Finder.app
- [x] click the *delete icon* and it should pop up a confirmation dialog to remove it
- [x] click the *cancel* button on the delete dialog and check if it cancels the dialog
- [x] click the *pause* button and verify all network activity halts
- [x] click the *resume* button and verify it is resumed completely

#### advanced use cases
- [x] share a dat using Dat CLI and try to import it into the desktop
- [x] create new dat in desktop and clone it using Dat CLI
- [ ] share dat on another machine using Dat Desktop and import it to your local desktop app
- [ ] create new dat in local Dat Desktop and import it on Dat Desktop running on a remote machine

#### app progress indicator
- [x] there is no progress indicator by default
- [x] while downloading dats, their cummulative progress set the app's progress indicator
- [x] having paused and unfinished dats in the list doesn't keep the progress indicator active
- [x] once all downloads finished, the progress indicator is cleared again

**Comment by juliangruber** [comment]
when hovering over an active dat's hex, it's not showing the `paused` state

<img width="271" alt="screen shot 2017-04-04 at 09 48 23" src="https://cloud.githubusercontent.com/assets/10247/24646347/dca73fa6-191b-11e7-9494-81378bb50dba.png">

**Comment by juliangruber** [comment]
replication between @Kriesse's dat-desktop and mine didn't work, investigating. dat-cli + dat-desktop did work.

**Comment by yoshuawuyts** [comment]
Think this is done (:

**Comment by juliangruber** [comment]
unfortunately not, i just haven't had the chance to debug the network issues with 2 machines. thinking i'll try with my vm setup, maybe that helps

**Comment by juliangruber** [comment]
ok, with the VM setup peers can't seed with each other unless there's globally reachable peers, like with our featured dats. so i'll need to get myself access to another laptop to debug more

**Comment by juliangruber** [comment]
let's do a new round of QA for the next release
