### ISSUE TITLE
Error on launch when dat-node sharing previous dat

### ISSUE THREAD

**Issue by rnkn** [datproject/dat-desktop#325]
I get the following error...

> ### Opps, something went wrong
> multidat: error creating multidrive

...if I have dat-node (12.0.3) sharing a dat previously created and saved inside Dat.app (1.1.1.723).

I realise it's silly, but might be a more-common-than-expected use.

To reproduce:

1. create a dat `foo` in Dat.app
1. close Dat.app
1. in shell, navigate to `foo`
1. `dat share .`
1. open Dat.app

Expected results:

Hmm not sure. Maybe a warning to dismiss, then dat `foo` is not listed?

Actual results:

Error as above. Dat `foo` is not listed. *Import dat* and *Create dat* buttons are missing.

**Comment by karissa** [comment]
It would be nice if they were compatible, definitely!

**Comment by juliangruber** [comment]
Is the `dat share` still running while you open the app?

**Comment by rnkn** [comment]
Yes this is with `dat share` still running.

**Comment by juliangruber** [comment]
ok, then this is a currently known limitation of our dat stack. We're working on a solution here currently, which involves showing problem dats instead of aborting all together: https://github.com/datproject/dat-desktop/pull/302

**Comment by juliangruber** [comment]
this has been merged and you now see an error message instead
