### ISSUE TITLE
paused hex icon state

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#326]
when hovering over the dat icon hex, ideally the `pause` icon will be shown

**Comment by Kriesse** [comment]
@juliangruber I can't solve this with CSS – on hover, the icon needs to change, which means changing the markup. Any ideas how to do that?
https://github.com/datproject/dat-desktop/blob/master/elements/table-row.js#L298

**Comment by juliangruber** [comment]
PR in #389
