### ISSUE TITLE
progress calculation off

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#330]
One dat keeps staying at `99%` although the uploading dat cli instance reports it's done. The `.progress` value calculated for said dat is

```js
stats.blocksProgress / stats.blocksTotal = 0.9995090475522513
```

What is the error here? @joehand are you aware of such a case and handling it in the cli already?

**Comment by juliangruber** [comment]
We could "simply" round values with a sane precision, but this could lead to different bugs as well

**Comment by yoshuawuyts** [comment]
Hmm, blocks not lining up feels like an error we should fix - rounding up
feels like we'd move the problem to the UI layer which seems a bit icky.

**Comment by karissa** [comment]
Will this get fixed in the new version?

**Comment by juliangruber** [comment]
I haven't seen this since SLEEP, so closing and hoping it won't reappear :)
