### ISSUE TITLE
styling of failed dats

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#341]
![screen shot 2017-04-27 at 15 40 33](https://cloud.githubusercontent.com/assets/10247/25485930/e54054b2-2b5f-11e7-913c-e3b41942bdc8.png)

While we display the error message when a dat fails to load - for example because it is already being served via the cli - the styling should be improved.

**Comment by Kriesse** [comment]
@julian Looks like a styling issue that'll come up again for other errors on a dat, how can we make it so that it's easy to re-use (and reproduce for me locally)?

**Comment by Kriesse** [comment]
@yoshuawuyts As per discussion, let's get this fixed – can you point me to where to get started with styling?

**Comment by juliangruber** [comment]
@Kriesse one way to reproduce is to create a dat in desktop, quit desktop, share the dat via cli, and while still sharing open desktop again

**Comment by juliangruber** [comment]
@Kriesse I think in `elements/table-row.js` you need to look at `errorRow()` for the DOM that's generated and add a css block for this as well.

**Comment by Kriesse** [comment]
> one way to reproduce is to create a dat in desktop, quit desktop, share the dat via cli, and while still sharing open desktop again

@juliangruber ha, just tried that, but that only gives me the error in the CLI :)
any ideas?

**Comment by juliangruber** [comment]
oh, what error are you getting in the cli?

**Comment by juliangruber** [comment]
was desktop maybe still running while you started the cli?

**Comment by juliangruber** [comment]
this is done in master :)
