### ISSUE TITLE
fix reload behavior

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#351]
Currently the app quits when you issue reload, via `CMD+R` for example. This is because we override `window.onbeforeunload` [here](https://github.com/datproject/dat-desktop/blob/master/models/dats.js#L74) and then always issue `app.quit()`, however we shouldn't do that when the action is to reload and not quit. We can probably check the event object to figure out which case it is.

**Comment by clkao** [comment]
Can we just do `manager.closeAll` in beforeunload without calling app.quit? assuming that for actually closing the app, electron will eventually do app.quit.  All we need is to cleanup the running state properly, right?

**Comment by juliangruber** [comment]
https://github.com/datproject/dat-desktop/blob/master/models/dats.js#L76 prevents the default behavior, we need to make sure it waits with closing the app until all dats are closed.

This might not be a requirement with sleep any more however, since it's not using dat-worker currently, which required this patch.

**Comment by clkao** [comment]
right, this does seem indeed tricky. apparently there's no way to wait for beforeunload :/

**Comment by karissa** [comment]
Yeah maybe app.quit isn't required at all anymore

**Comment by juliangruber** [comment]
this logic has been removed completely in the SLEEP branch, @Kriesse can we continue using this as our working branch?

**Comment by juliangruber** [comment]
fixed once we merge SLEEP
