### ISSUE TITLE
slim down app

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#36]
The dmg is currently 88.7 MB in size :|

**Comment by zeke** [comment]
How do you plan to make it smaller?

**Comment by zeke** [comment]
Maybe this would help? https://github.com/electron-userland/electron-packager/issues/235

**Comment by yoshuawuyts** [comment]
We could use [disc](https://github.com/hughsk/disc) to start optimizing our bundle sizes

**Comment by juliangruber** [comment]
solved by the 2 package.json architecture

**Comment by zeke** [comment]
@juliangruber I see you're not using electron-builder. Did you try it and have problems with it?

**Comment by juliangruber** [comment]
@zeke working on a pr to add it :)
