### ISSUE TITLE
Edit Dat Name: don't show edit indicator when Read-only

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#363]
When a dat is read-only, there should be no visual hover indicating that it can be edited (it can not): 

<img width="298" alt="screen shot 2017-05-15 at 4 21 14 pm" src="https://cloud.githubusercontent.com/assets/53684/26062288/b3ee29dc-398a-11e7-85e1-5ee337b0385c.png">

**Comment by juliangruber** [comment]
fix in https://github.com/datproject/dat-desktop/pull/364

**Comment by juliangruber** [comment]
landed!
