### ISSUE TITLE
Wrong color on icon next to peers

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#365]
When peers are `N\A`, the icon should be grey, not green

![image](https://cloud.githubusercontent.com/assets/53684/26101573/e564e364-3a31-11e7-8f00-74a47ea5461d.png)

**Comment by juliangruber** [comment]
pull request in https://github.com/datproject/dat-desktop/pull/368

**Comment by yoshuawuyts** [comment]
yay, merged!
