### ISSUE TITLE
deleting the first dat causes rendering issues

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#384]
<img width="834" alt="screen shot 2017-05-19 at 11 30 28" src="https://cloud.githubusercontent.com/assets/10247/26249711/e512ce30-3ca7-11e7-8a04-6135b0e189d6.png">

**Comment by juliangruber** [comment]
the list is empty and placeholder elements will be rendered

**Comment by yoshuawuyts** [comment]
I think this can be closed, despite https://github.com/shama/bel/pull/77 not being merged yet - very close!
