### ISSUE TITLE
refactor recursive file walk in download screen

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#391]
use @mafintosh's mirror-folder module for this

**Comment by juliangruber** [comment]
tough choice, with mirror-folder it's slower, but potentially safer, since it's all sequential and we just run all in parallel.

I have a branch ready with this here: https://github.com/datproject/dat-desktop/compare/mirror-folder?expand=1

Let's see with more usage of the new download screen which is the better approach.

**Comment by yoshuawuyts** [comment]
new code looks pretty good! :sparkles:

**Comment by juliangruber** [comment]
merged the new code in as limited concurrency would help unblocking the render thread
