### ISSUE TITLE
share button too big after fresh npm install

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#392]
![screen shot 2017-05-23 at 18 59 06](https://cloud.githubusercontent.com/assets/10247/26366054/e824bd96-3fe9-11e7-87a7-12763e17d6de.png)

Just noticed this when looking at the travis build, and this also happens locally after a good old `npm cache clean && npm install && npm start`

**Comment by Kriesse** [comment]
Ha, did all of the above and can't reproduce!
Looks like this:
![image](https://cloud.githubusercontent.com/assets/53684/26376670/9da08ad8-400d-11e7-8100-f83b9c04b753.png)

@juliangruber Could you inspect the larger button and see what's the origin of the wring style?

**Comment by juliangruber** [comment]
The download text has `font-size: .75rem`, while the button only inherits `font-size: 100%`.

does that help?
