### ISSUE TITLE
pause hover fires unexpectedly

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#394]
<img width="115" alt="screen shot 2017-05-23 at 19 24 17" src="https://cloud.githubusercontent.com/assets/10247/26367007/74928f9e-3fed-11e7-8503-c087ab2be619.png">

**Comment by yoshuawuyts** [comment]
Does this have anything to do with the "mouseenter" event triggering?

**Comment by juliangruber** [comment]
fix in https://github.com/datproject/dat-desktop/pull/396
