### ISSUE TITLE
deleted dat is added back

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#403]
@Kriesse:

> If I delete a dat from the desktop app, and also delete the folder via Finder, then refresh the app, the deleted dat comes back. And the folder is created as well.

**Comment by juliangruber** [comment]
I can't reproduce, maybe that's part of an outdated dependency. Can you try to reproduce with a fresh set of dependencies?

**Comment by Kriesse** [comment]
@juliangruber Yup, can't reproduce it anymore either, closing!
