### ISSUE TITLE
open download input is closed when UI rerenders

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#411]

**Comment by juliangruber** [comment]
there's no DOM modifications happening here, pure CSS. I think the input is losing its active or focus status. @yoshuawuyts have you seen this before?

**Comment by yoshuawuyts** [comment]
@juliangruber got a screenshot of what happens?

**Comment by juliangruber** [comment]
@yoshuawuyts when you have the download input open while downloading a dat, when eg the download speed updates the input will be closed again

**Comment by Kriesse** [comment]
@juliangruber Has this been fixed? I can't reproduce.

**Comment by juliangruber** [comment]
Yes, this has been fixed! :)
