### ISSUE TITLE
.line-loading animation take +/- 50% CPU

### ISSUE THREAD

**Issue by G-Ray** [datproject/dat-desktop#413]
When disabling animation on .line-loading, CPU load is low.
When the animation is enabled, it takes +/- 50% on my 4 threads CPU.

I think chromium/electron GPU acceleration is not enabled on Linux. I don't know if GPU accel could help much, but still, 50% is high!

**Comment by yoshuawuyts** [comment]
dang yeah, that's no good. Cc/ @kriesse - should this be turned off?

**Comment by juliangruber** [comment]
we also have a web version of this animation here: http://datproject.github.io/design/

can you see if this gives you the same kind of performance in a regular browser on your machine?

**Comment by Kriesse** [comment]
@juliangruber @yoshuawuyts Looking into this –I can reproduce high CPU load when downloading a dat, but not sure it's tied to the animation, but maybe the fact that we have a full repaint every time the download speed updates – trying to figure out what is happening exactly. @juliangruber let's debug together?

**Comment by juliangruber** [comment]
@G-Ray what's your linux setup?

**Comment by juliangruber** [comment]
let's first try to reproduce :)

**Comment by G-Ray** [comment]
@juliangruber @Kriesse I confirm that when I open http://datproject.github.io/design/ my cpu is around 50%.

My setup: Fedora 25 + chromium 58 on a xps-13 (i7-7500u)

**Comment by juliangruber** [comment]
cool, i'll try later with my ubuntu vm!

**Comment by juliangruber** [comment]
I can confirm, this is the same on my ubuntu vm. @Kriesse shall we disable the animation on linux?

**Comment by Kriesse** [comment]
@juliangruber Yup, works for me!

**Comment by juliangruber** [comment]
#428
