### ISSUE TITLE
Reset Password Screen

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#414]
Similar to datproject.org:

![image](https://user-images.githubusercontent.com/53684/26926498-3f6f72c4-4c4e-11e7-9d29-4914df9e2598.png)

**Comment by juliangruber** [comment]
how do we navigate away from this screen?

**Comment by juliangruber** [comment]
besides this, the js part should be done

**Comment by Kriesse** [comment]
@juliangruber 

Good point about navigating away – we need this for all 3 screens (register, login, password). Right now the user is stuck.

Could we do something similar to what Slack does?
- hide header
- show "x" close button
- when "x" is clicked, go back to previous screen

I guess this means a modal after all 🙈 

![image](https://user-images.githubusercontent.com/53684/27023866-a9f79dd4-4f54-11e7-97b9-b00f4640d913.png)

Alternatively, we could add a menu item "overview" or "home" to the header, which would always bring you back to the overview screen.

**Comment by juliangruber** [comment]
👍 i think this is the way to go!

**Comment by Kriesse** [comment]
Opened a separate issue for making these screens a modal: https://github.com/datproject/dat-desktop/issues/425

**Comment by Kriesse** [comment]
Styling done, closing
