### ISSUE TITLE
Header shows user avatar when logged in

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#415]
Mockup: 

![image](https://user-images.githubusercontent.com/53684/26935064-48fba8b8-4c6b-11e7-824e-931d57bb5955.png)

**Comment by juliangruber** [comment]
js part of this should be done :)

**Comment by Kriesse** [comment]
Updated the styling a bit for better readability:

![image](https://user-images.githubusercontent.com/53684/27022947-9dec538a-4f50-11e7-9eef-4480fd070138.png)
