### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#423]
- [x] bar
- [x] total down/up speed
- [x] styles

**Comment by juliangruber** [comment]
@Kriesse ready to take over, in the `status-bar` branch! :)

**Comment by juliangruber** [comment]
![screen shot 2017-06-13 at 10 35 38](https://user-images.githubusercontent.com/10247/27073415-0e895eac-5024-11e7-9cb2-8fb1d9a8746a.png)

**Comment by Kriesse** [comment]
done!
