### ISSUE TITLE
browserify step fails with "Unterminated regular expression"

### ISSUE THREAD

**Issue by ralphtheninja** [datproject/dat-desktop#436]
I get a really strange error during `npm install`. Somehow browserify thinks the slash in `</p>` is the beginning of a regular expression. Using node 8.3.0, but get the same error in node 7 (which is used by travis).

```
$ node scripts/browserify.js 
Thu Aug 17 2017 01:19:12 GMT+0200 (CEST) bundling…events.js:182
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unterminated regular expression (212:12) while parsing file: /home/lms/src/datproject/dat-desktop/elements/modal.js
    at Parser.pp$4.raise (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2610:13)
    at Parser.pp$8.readRegexp (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:3285:38)
    at Parser.pp$8.readToken_slash (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:3103:51)
    at Parser.pp$8.getTokenFromCode (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:3229:17)
    at Parser.pp$8.readToken (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2975:15)
    at Parser.pp$8.nextToken (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2966:15)
    at Parser.pp$8.next (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2923:8)
    at Parser.pp$3.parseTemplateElement (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2235:8)
    at Parser.pp$3.parseTemplate (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2254:38)
    at Parser.pp$3.parseSubscripts (/home/lms/src/datproject/dat-desktop/node_modules/acorn/dist/acorn.js:2001:29)
```

**Comment by ralphtheninja** [comment]
I am on commit 29c0329, have also tried `npm run burnthemall` but no luck.

**Comment by ralphtheninja** [comment]
I have tried on two machines and get the same error. I simply can't install dat-desktop on linux. Would be nice if someone else could try to reproduce on some other machines, just to rule out my machines being borked somehow.

**Comment by joehand** [comment]
@ralphtheninja just tried on Mac OSX and it worked from a fresh git clone & npm install. So maybe a linux issue?

**Comment by ralphtheninja** [comment]
@joehand Aye, seems like it. I think some of you osx users would have noticed this otherwise :)

**Comment by juliangruber** [comment]
it does build on travis, with all the integration tests, so we _should_ have noticed OO

**Comment by ralphtheninja** [comment]
> it does build on travis, with all the integration tests, so we should have noticed OO

Aye, I noticed this as well. The last build was done a month ago though, so we know it worked a month ago. It probably still does, but could someone be kind to restart the latest build?

**Comment by ralphtheninja** [comment]
If I comment out the `sheetify/transform` in `lib/browserify.js` it works

**Comment by juliangruber** [comment]
I restarted the build https://travis-ci.org/datproject/dat-desktop/builds/251701118 :)

@yoshuawuyts have you noticed this?

**Comment by ralphtheninja** [comment]
Tada!

**Comment by ralphtheninja** [comment]
One thing that I noticed is that npm that comes with node 7 doesn't abort, it continues to install even though this step fails. However node 8 does abort immediately, so maybe we should add node 8 to .travis.yml as well

**Comment by ralphtheninja** [comment]
I think I've managed to pin point the problem. If I change `package.json` to use `sheetify@6.1.0` it works, so I suspect something in https://github.com/stackcss/sheetify/commit/3f8adb448370d69e7c97c15753d370912158e3f4 might have to do with it.

As a side note, `package-lock.json` seems deceptive to me, since it actually points out `6.1.0` (it should use that version with node 8, right?), npm still installs `sheetify@6.1.1`.

Also if you check previous successful builds, they also use `sheetify@6.1.0` https://travis-ci.org/datproject/dat-desktop/jobs/251073858#L1150

**Comment by yoshuawuyts** [comment]
oh, no! - I haven't been paying attention lately

**Comment by ralphtheninja** [comment]
Ok, figured out why _I_ am having problems on node 8 and node 7 but travis only has problems on node 7 but not on node 8.

I have a global npm config set that doesn't care about `package-lock.json`, so when I install `dat-desktop` I always get `sheetify@6.1.1`, but travis get `sheetify@6.1.0` due to fixed version in `package-lock.json`.

So this should fail on OSX as well if you put `package-lock=false` in `~/.npmrc`

**Comment by joehand** [comment]
@ralphtheninja ah yes, was able to reproduce it with that.
