### ISSUE TITLE
Run as web server?

### ISSUE THREAD

**Issue by jivank** [datproject/dat-desktop#437]
Would it be possible to run this as a webserver for remote management? Might need a way to authenticate/secure but it could be useful for headless setups like a Raspberry Pi.

**Comment by joehand** [comment]
Hey, we have some command like tools that are be more suited for that https://github.com/datproject/dat or https://github.com/mafintosh/hypercored.

**Comment by MAccadia** [comment]
Hi, I think @jivank wanted to have the same graphical interface than dat-desktop on a web page / web server. I think it would be nice too, but this repo is for dat-desktop, so...

**Comment by okdistribute** [comment]
This is something we're working on this year, will report back when there's a prototype.
