### ISSUE TITLE
path.join in dats.js causes problems with windows

### ISSUE THREAD

**Issue by pmario** [datproject/dat-desktop#443]
Hi folks,

TLDR; Are there any plans to support windows at this state of the project?

-------------------

Just tried to compile and run the project on windows 10. .... Many manuals steps needed, since bash build scripts fail, atm. .... 

System seems to fail at startup already. ....

It seems this line https://github.com/datproject/dat-desktop/blob/f8c71b4c974f2c8f2e0e0b9c778f747c830486dd/models/dats.js#L44

causes a problem with an `undefined` path ... 

Solution seems to be something like this: https://stackoverflow.com/questions/9080085/node-js-find-home-directory-in-platform-agnostic-way

**Comment by juliangruber** [comment]
Thank you for trying it out and submitting this issue. The fix for this particular one should be here: https://github.com/datproject/dat-desktop/pull/444

**Comment by pmario** [comment]
@juliangruber This fix/home-on-windows branch seems to work. .... __but__ After the intro, where I could type "next" ... 

I do get this: 

![dat-desktpo-after-intro](https://user-images.githubusercontent.com/374655/33235139-7ee3e984-d232-11e7-9cb5-259aa2b18d45.gif)

I suppose, I should be able to click the "download" or the "share a folder" buttons / links or whatever. ... But I can't ...  and there are now commands in the toolbar. 

Do I miss something?

**Comment by juliangruber** [comment]
TBQH you have gotten the furthest of anyone making dat-desktop work on windows 👏. Underlying libraries used to not be compatible with it but now maybe they are?

**Comment by pmario** [comment]
Yea. IMO it has been a problem with: utp-native ... Which seems to be fixed with the latest version. 
I did need to install it manually. ...

I will need to spin up a new and clean windows VM, to have a look, what's needed for a working dev environment. ... My main system may have dependencies installed already, which will definitely throw problems on a "vanilla" windows system. ... 

By the way. ... The tests pass on ubuntu but they fail on windows - powershell.

**Comment by karissa** [comment]
Yeah, dat cli works on windows now, exciting! Thanks for looking at this!

**Comment by pmario** [comment]
There seem to be some init-problems and the build scripts need to be modified, to work with win too. 
I did check the build dependencies for a vanilla windows system

 - https://git-scm.com/
 - https://nodejs.org/en/
 - https://www.npmjs.com/package/windows-build-tools

windows build tools should be installed like this: 

**Powershell as Admin**

```
npm --add-python-to-path install --global windows-build-tools
```

 - git and node, have windows installers, that work OK and add all the paths. 
 - Finally `.\node_modules\.bin` should be added to the windows environment variables 

------------

 - The existing build process will fail, since somewhere utp-native 1.5x is used instead of 1.6.x, which will cause `npm install` to fail. 

 - A manual install of `utp-native` will fix that. 
 - `  npm rebuild --runtime=electron --target="1.4.14" --disturl=https://atom.io/download/atom-shell   --abi="50" > log.txt` will build electron
 - `$env:NODE_ENV="development"` will assigne dev mode
 - `electron .` ... will start the system as shown with the screenshot. 

There are still a lot of problems to fix. ... BUT imo that's a starting point.

**Comment by juliangruber** [comment]
I've assigned this to me for now and will try to get this running this week (unless there are major blockers)

**Comment by pmario** [comment]
If I can help. Let me know.

@pfrazee seems to have a working toolchain for beaker browser. May be he can share some info.

**Comment by juliangruber** [comment]
i updated the dependencies, rewrote the build script in cross platform js and enabled app veyor again. let's see what happens

**Comment by juliangruber** [comment]
the reason for ui errors seems to be that we're using a frameless window _and_ an application menu. on mac the application menu can be displayed outside the dat-desktop window in the menu bar, on windows however that's not possible:

![screen shot 2017-11-30 at 19 49 10](https://user-images.githubusercontent.com/10247/33448914-8ef616e8-d607-11e7-9e3b-26eb8390eb66.png)

**Comment by juliangruber** [comment]
it could also be choo related, the DOM is missing the header DOM:

![screen shot 2017-11-30 at 20 44 56](https://user-images.githubusercontent.com/10247/33451441-5c6402f0-d60f-11e7-9e0f-168aaa51ada5.png)

I'll try updating more dependencies (I did update electron).

**Comment by pmario** [comment]
The funny thing is, that I sometimes see the menu. .. But I couldn't find out, how to reproduce it. ...

**Comment by juliangruber** [comment]
> The funny thing is, that I sometimes see the menu. .. But I couldn't find out, how to reproduce it. ...

yes! i saw it once but then couldn't reproduce any more either

**Comment by pmario** [comment]
Just tested latest master, and the project compiles and starts. ... So I'll close this issue, and create new ones, when I have time to do more tests. @juliangruber Thx for your support!
