### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by baimafeima** [datproject/dat-desktop#447]
> To run the app locally check out our download guide or install directly from the command line using Homebrew Cask. Currently only MacOS is supported.

In your download section it says that currently only MacOS is supported. When will you add support for Linux-based operating systems?

**Comment by joehand** [comment]
Hello! We do support Linux, check out the [installation page](https://docs.datproject.org/install). Looks like we need to update the readme here. PR welcome if you want to update that!
