### ISSUE TITLE
Question: tap or tape?

### ISSUE THREAD

**Issue by martinheidegger** [datproject/dat-desktop#454]
Right now two test frameworks are used in the tests: `tap` for the integration tests and `tape` for the unit tests. As far as I understand the two of them are very similar - with `tap` being the more robust one while `tape` being able to run in the browser. Wouldn't it be reasonable to drop one in favor of the other?

**Comment by yoshuawuyts** [comment]
uehhhh, yeah either one works - I've always been using `tape` because it feels more stable, but have no strong feelings about any of these either way!

**Comment by juliangruber** [comment]
I think I at one point wanted to drop one or the other but there was a problem with promise support...yeah I think that was it: tape doesn't (or didn't) support promises, however the unit test code needs to be browserified and therefore can't run tap. Maybe things have changed now though!

**Comment by martinheidegger** [comment]
`tape` doesn't support promises. `tap` does. It is true that tap isn't browserified. There is an  [opn PR](https://github.com/tapjs/node-tap/pull/356) though. Anyways: I couldn't find a place in the tests where they need to be browserified?!

**Comment by juliangruber** [comment]
> I couldn't find a place in the tests where they need to be browserified?!

You're right about that. Actually, this test needs to be executed in an electron renderer context: https://github.com/datproject/dat-desktop/blob/master/tests/dat-manager.js. I think that was the part that didn't work with tap, only tape

**Comment by martinheidegger** [comment]
On my test branch I tried to switch over entirely to tap and it did work, with some tricks, within electron as well.

**Comment by martinheidegger** [comment]
Switched to `tap` in https://github.com/datproject/dat-desktop/pull/453/commits/246804a3e534b9a79f6f492c94203779e43ccb56
