### ISSUE TITLE
Style Sharing Modal

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#46]
Current status:

![image](https://cloud.githubusercontent.com/assets/53684/18583297/1378a07e-7c0a-11e6-90ad-f2c4e549b8c4.png)

Related: https://github.com/datproject/dat.land/issues/255

**Comment by juliangruber** [comment]
It could very well be that we need to roll our own modal implementation for this, as it's the js-alert lib right now. But maybe if all it takes is adding some css, that would be great too

**Comment by karissa** [comment]
We could also do something really simple with `node-notifier`

example I use in ye old dat-menubar: https://github.com/karissa/dat-menubar/blob/master/app.js#L52

**Comment by Kriesse** [comment]
@juliangruber I find the current modal implementation hard to style. All the styles/icons are hard-coded in the `js-alert` module, there don't seem to be any options. Any suggestions? 

FYI, Mockup:
![image](https://cloud.githubusercontent.com/assets/53684/20596560/144e60fa-b27a-11e6-8776-5668ae951146.png)

**Comment by juliangruber** [comment]
@Kriesse agree, I saw this coming but went for the "works right now" solution to have something to start with. Let's make this our own little component. cc @yoshuawuyts

**Comment by Kriesse** [comment]
@juliangruber Cool, I figured (actually super helpful to see a quick working solution to figure out the UI details!)
Happy to style our own little component, just need a starting point :)

**Comment by juliangruber** [comment]
nice! I think @yoshuawuyts this is where you take over, right?

**Comment by yoshuawuyts** [comment]
Yup!

**Comment by yoshuawuyts** [comment]
Going to be switching to https://github.com/shama/modal-element

**Comment by yoshuawuyts** [comment]
#99 was merged and opened #103 - closing this issue in favor of #103
