### ISSUE TITLE
Delete dat

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#464]
- [x] confirmation modal -> https://github.com/datproject/dat-desktop/pull/482/
- [X] delete dat
- [X] state errors deleting a dat (https://github.com/datproject/dat-desktop/commit/f39372cab6bcc7d326b282da3e9b10bf7046b83b)

**Comment by juliangruber** [comment]
hey @aks-, shall we add you to this project? :)

**Comment by juliangruber** [comment]
Pull request here: https://github.com/datproject/dat-desktop/pull/459

**Comment by aks-** [comment]
@juliangruber I would love to be part of project :D

**Comment by juliangruber** [comment]
@aks- I've asked the team about this, it looks like you'd be the first "inofficial" contributor. I'll respond back here!

**Comment by aks-** [comment]
@juliangruber that's exciting, THANK YOU :)
