### ISSUE TITLE
tons of memory!

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#47]
<img width="997" alt="screen shot 2016-09-22 at 2 29 01 pm" src="https://cloud.githubusercontent.com/assets/633012/18748087/01a7e014-80d1-11e6-9a84-d5e6d0d41c58.png">

Downloading a 5GB dat, dat-desktop is using almost 4GB of memory

**Comment by juliangruber** [comment]
can you compare that to how much memory `dat(1)` uses for the same task?

**Comment by karissa** [comment]
good q!

It wrecks my cpu but memory doesn't seem to go that high that fast.
<img width="605" alt="screen shot 2016-09-22 at 4 25 31 pm" src="https://cloud.githubusercontent.com/assets/633012/18751973/3534653c-80e1-11e6-81ae-e2118bbe41d7.png">

**Comment by juliangruber** [comment]
let's revisit this once we moved to dat-js

**Comment by yoshuawuyts** [comment]
I don't think this is blocked any longer

**Comment by juliangruber** [comment]
we're not doing anything special here any more, just connecting dat-node and choo basically. Let's revisit this when it becomes a problem again.
