### ISSUE TITLE
move to datproject?

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#48]
I think it is almost time to move this to datproject/ and focus on it hard! would love to also chat about priorities for the desktop app and see what's needed to take it next level! Happy to help code with you on the next sprint, too

**Comment by juliangruber** [comment]
What about we move it to datproject/ once progress indicators work? Those are kind of the only "embarrassing" things left to fix imo.

**Comment by Kriesse** [comment]
ping @juliangruber

**Comment by juliangruber** [comment]
<img width="314" alt="screen shot 2016-10-21 at 15 39 16" src="https://cloud.githubusercontent.com/assets/10247/19600266/8d70fda8-97a4-11e6-8a6f-0edccd3afb1f.png">

**Comment by clkao** [comment]
Apparently this is done.
