### ISSUE TITLE
Error: Could not get code signature for running application

### ISSUE THREAD

**Issue by fredhampton** [datproject/dat-desktop#485]
I ran npm run dist   
Received this error when after I installed the dmg 
Error: Could not get code signature for running application

**Comment by juliangruber** [comment]
This is expected: if you sign the application yourself, you need to have the proper code signing certificates in place.

If you just want to run the app on its own, `npm start` should be fine.

If you want to run an official build, check out https://github.com/datproject/dat-desktop/releases
