### ISSUE TITLE
Linux version refers to Apple™ software product

### ISSUE THREAD

**Issue by medavox** [datproject/dat-desktop#527]
The tooltip popup for downloaded archives says 'open in finder'.
Clicking that button does nothing for me on Linux Mint 17.

file manager support seems to be broken on Debian flavours of Linux.

**Comment by dkastl** [comment]
I also think, that `Open in Finder` is too much OSX-specific. 

Each OS has it's name, but in my opinion something like `Open in file manager` sounds acceptable for everyone, see https://github.com/dat-land/dat-desktop/commit/8aba015e96416cc0051024d982d4624f6d3d9b80

Clicking on the button works (again) in the upcoming 3.0.0 release.

**Comment by okdistribute** [comment]
I think this is fixed now.
