### ISSUE TITLE
Add Menu Icon + Dropdown

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#53]
for now, including
- account placeholder
- software author & twitter
- submit issue
- version
- "Built with 🐈  by Dat"

**Comment by Kriesse** [comment]
Mockup:
![image](https://cloud.githubusercontent.com/assets/53684/20515778/41959090-b0ce-11e6-8c86-6fd524313c16.png)

**Comment by yoshuawuyts** [comment]
We've temporarily removed the menu; marking this as priority low. Probably related to the login and logout feature

**Comment by Kriesse** [comment]
Styles for this are done, just hidden (`.dn`). Closing in favor of #134 and #135.
