### ISSUE TITLE
Show dialog when user tries to download existing dat

### ISSUE THREAD

**Issue by dkastl** [datproject/dat-desktop#546]
We run into a tricky issue when the user tries to download the same DAT more than once: Should we add the new download to the list? Should we download it a second time to the folder?

The easiest solution for this would be to simply show an alert dialog:

```javascript
alert('This DAT is already added to the list.')
```

and:

```javascript
alert('This DAT has already been download. Using the downloaded version')
```

... in case that DAT exists on the Hard-disc but not in the DAT list.

**Comment by dkastl** [comment]
@aks- , could you tell me about the state of this to-do (that I just turned into an issue to be able to contact you)?

You placed it in the "in progress" column. That's why I'm asking:
https://github.com/dat-land/dat-desktop/projects/1

**Comment by martinheidegger** [comment]
The dialog has been added and tested - quite a bit.
