### ISSUE TITLE
Dat-Links for tests and development

### ISSUE THREAD

**Issue by AtuyL** [datproject/dat-desktop#559]
I think need below.

- [ ] Normal
- [ ] Large
- [ ] Will be Error
- [ ] 0 byte Dat
- [ ] Only have "Author"
- [ ] Only have "Description"
- [ ] Have "Author" and "Description"

If can be creation the below, LGTM.

- [ ] Scheduled

 changing file. (it is automatically

**Comment by dkastl** [comment]
@AtuyL , how do you define "Normal" and "Large"? What would be a good size in your opinion? Shall we also take into account the number of files?

**Comment by dkastl** [comment]
@AtuyL @martinheidegger , what would be a good example for a corrupted Dat (one with an error)?

**Comment by AtuyL** [comment]
@dkastl san, Thank you for creating. I'll try it for development.

**Comment by dkastl** [comment]
@AtuyL , maybe the "dynamic" test will not work as I expected. And the URL will be only read-only on any device but where I created the archive.

So any "static" Dat archive should be OK, but adding `.dat` directory probably doesn't make much sense... except for myself ;-)
