### ISSUE TITLE
Package name `dat-desktop`

### ISSUE THREAD

**Issue by dkastl** [datproject/dat-desktop#572]
@martinheidegger , @AtuyL just saw, that the package name is now `Dat-...` again. 

![screenshot from 2018-11-08 14-22-33](https://user-images.githubusercontent.com/227762/48179331-01b8f980-e362-11e8-97a0-6d44ad55e41c.png)

I think `dat-desktop-...` is a better name for the application binary.

![screenshot from 2018-11-08 14-22-43](https://user-images.githubusercontent.com/227762/48179349-257c3f80-e362-11e8-8e1c-413ccf0333bd.png)

**Comment by martinheidegger** [comment]
I agree.
