### ISSUE TITLE
Weird rendering glitches

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-desktop#60]
Probably electrons fault, but posting here because both @clkao and I noticed it when running the `auth0` branch. Issue is flickering when rendering CSS shadows/semi opaque overlays

Video: https://drive.google.com/open?id=0B8lSLF293vHqZkhoT004UTd1b3M

**Comment by yoshuawuyts** [comment]
This seems to be because of the styles included with the `auth0` login widget. There seem to be multiple transitions that interact oddly with each other. We probably want to implement our own login screen to match the designs we have, so that should provide a resolution for this issue

**Comment by Kriesse** [comment]
@yoshuawuyts @maxogden Can we close this (as we are probably not going to use this widget)?
