### ISSUE TITLE
[feature] migrate to choo

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#61]
As per https://github.com/juliangruber/dat-desktop/issues/57 we should migrate the logic to `choo`.

[ steps tbi, need to read source to figure out what the order is ]

**Comment by yoshuawuyts** [comment]
Looked at the code, seems like it should be a reasonably straight forward migration - fingers crossed it also turns out to be that way

**Comment by Kriesse** [comment]
PR ready for review here: https://github.com/datproject/dat-desktop/pull/71

**Comment by yoshuawuyts** [comment]
This done now
