### ISSUE TITLE
Small text on High DPI displays

### ISSUE THREAD

**Issue by evdubs** [datproject/dat-desktop#628]
I am running the v2.0.0 AppImage release of dat-desktop. The text is tiny as I am running at a 4K resolution and I have "large text" enabled in Ubuntu 18.10 so that I can read application text. Embedded browser engines like Electron sometimes do not inherit this "large text" setting and so the text is tiny. Usually, the way I solve this issue is just by zooming in. However, when I try Ctrl-+ or Ctrl-Mouse Wheel, no zooming happens. Is there a way to zoom in dat-desktop?

**Comment by okdistribute** [comment]
Can you try this again with 3.0.1?

**Comment by evdubs** [comment]
Success!
