### ISSUE TITLE
[infrastructure] Automated Builds

### ISSUE THREAD

**Issue by karissa** [datproject/dat-desktop#63]
We should have a way to automate builds; e.g. enable a (CI) servers to create
the appropriate builds, tags and github release. This way we can get into the
habit of releasing early and often, which creates momentum for the team and
project in general.

In addition to creating builds on release, it would be valuable to create
nightly builds that we can download and run to test features. This ties in to
https://github.com/juliangruber/dat-desktop/issues/67

**Comment by juliangruber** [comment]
dat-desktop now installs successfully on travis, osx and linux. Next: run the packaging jobs there too.

**Comment by juliangruber** [comment]
packaging now works on travis too, next: use travis new cron jobs to provide nightly builds

**Comment by Kriesse** [comment]
@juliangruber Is there a way to download the automated builds from Travis?

**Comment by juliangruber** [comment]
not yet, we need to make it upload those to github releases or somewhere else. I'll try creating a "nightly" release on github that each successful build will be uploaded to.

**Comment by juliangruber** [comment]
@Kriesse starting current #master, builds now always show up in the latest draft release! current one is https://github.com/datproject/dat-desktop/releases/tag/untagged-4024b3636b599fbc021c
