### ISSUE TITLE
Partial indexing

### ISSUE THREAD

**Issue by tiotrom** [datproject/dat-desktop#643]
It appears that when I share a folder with a lot of files in-it, it only indexes a few of them. When I try to re-add them it seems to "remember" all of that so I can't "reset" it. Despite deleting all the config files I could fine. I use Linux. Cheers!

**Comment by tiotrom** [comment]
I have to mention I use the appimage version (latest from here). I was also able to "reset" these folders by deleting the ".dat" folder from the shared folder. But it still struggles to index the folders.

**Comment by okdistribute** [comment]
@tiotrom do you see the same behavior with the dat cli tool? this will help us isolate the bug

**Comment by tiotrom** [comment]
Ok It seems to go through slowly by slowly. Little by little. It just looks as if it is stuck. Maybe it would be useful to add a progress bar or indicator when it is still indexing the files inside a folder. Much appreciated the latest improvements you did to this little app.

**Comment by okdistribute** [comment]
Ah yes this is a known issue with dat with many files, the newest version will drastically improve performance. We're still finding an eta on when that hits 1.0, check out progress here: https://github.com/andrewosh/hyperdrive-daemon
