### ISSUE TITLE
[infrastructure] updates

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#67]
Auto updates are important so that new users can enjoy the features we put out. This will improve their Dat experience, and prevents us with having to debug older versions.
- [x] auto download new app version whenever a new release is done, similar to how chrome does it
- [x] figure out signing on OS X (e.g. make it so the shell only has to be downloaded once, and is then verified by apple while still updating contents)
#### bonus
- [ ] switch to enable pulling down "nightly" builds, useful for Dat team members to dogfood the catch Dat desktop bugs early / try out new features immediately

**Comment by juliangruber** [comment]
We need to run a releases server for this, and luckily there's a project already that simply uses GitHub releases as a backend. @mafintosh can we get this deployed on one of your machines? 

https://nuts.gitbook.com/deploy.html

**Comment by juliangruber** [comment]
i could also just spin up at DO droplet and start billing it

**Comment by karissa** [comment]
We have freee digital ocean, let's use it

**Comment by Kriesse** [comment]
@juliangruber what's the status on this? any chance we have it this week still?

**Comment by juliangruber** [comment]
@Kriesse working on it today

**Comment by juliangruber** [comment]
@Kriesse in light of the issues with the "check for updates" menu bar item raised in the call, how do we progress with this UX wise?

What hyper does is pretty elegant IMO.

**Comment by Kriesse** [comment]
@juliangruber Cool, I like that pattern let's do the hyper-way then.

Note that this is a bit different from the modal we already have. I think this is the behavior we want:

- show a small, sticky notification that reads `Version X.X.X is ready. Restart to install`
- notification appears after restart when a new version is ready
- clicking "Restart to install" closes app and starts the update
- notification can be dismissed (by clicking X)

Question:
- if the notification is dismissed, when do we show it again?

![image](https://cloud.githubusercontent.com/assets/53684/21902219/ea16fed0-d8af-11e6-9d6f-c100d630e054.png)

**Comment by yoshuawuyts** [comment]
@Kriesse I believe Spotify hides the notification until the next time the application is booted; I think that could be reasonable

**Comment by juliangruber** [comment]
let's address nightlys later, for now this is done!
