### ISSUE TITLE
Style Empty States

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#68]
When a user opens Dat Desktop for the first time, what do they see?
When the list of dats is empty, what do they see?

- [x] style empty table state
- [x] style welcome screen

**Comment by Kriesse** [comment]
@yoshuawuyts I'd like two different pages here.

## 1. Welcome Page
User opens app for the first time and sees a welcome message. Buttons in header are hidden. The button removes this page and goes to the Empty State. Later we could add a more detailed click through tutorial. 
![image](https://cloud.githubusercontent.com/assets/53684/20951364/6dda79b6-bc79-11e6-817f-a5d54a3a8410.png)

## 2. Empty State
When there are no dats, user sees this (instead of an empty table). 
![image](https://cloud.githubusercontent.com/assets/53684/20951382/83025160-bc79-11e6-98ea-27ce048e384c.png)

**Comment by yoshuawuyts** [comment]
alright, #111 was merged - can all be styled now (:
