### ISSUE TITLE
Style Dat Status Icons

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#70]
Each Dat is displayed as a row which starts with an icon that indicates the state of the dat.

To Do:
- [x] list and name all possible states
- [x] mock up
- [x] create assets

**Comment by karissa** [comment]
related to dataset 'health' at all (https://github.com/datproject/dat.land-roadmap/issues/46)?

What do you mean by 'state' of the dat?

**Comment by juliangruber** [comment]
I think `downloaded`, `downloading`, `empty`, etc?

**Comment by Kriesse** [comment]
@karissa Yup, what @juliangruber said – this refers to the icon (currently a hexagon with an arrow) at the beginning of a dat line item. I'll come up with a suggestion in a mockup and will then need your feedback on whether I represented the states correctly :)

**Comment by Kriesse** [comment]
Eventually we need SVGs here, not only text. Mockup:
![image](https://cloud.githubusercontent.com/assets/53684/20517706/49061fee-b0d7-11e6-8ff7-60a28c4bb847.png)

**Comment by Kriesse** [comment]
@yoshuawuyts Question about: https://github.com/datproject/dat-desktop/blob/master/pages/main.js#L59

Instead of `↓`, how can I get something like this?
```
          <svg class="network-svg">
            <use xlink:href="#daticon-network" />
          </svg>
```
