### ISSUE TITLE
[discussion] desktop architecture

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#72]
# dat desktop architecture

I ran into some issues with `dat-desktop`'s technical design today. I'm writing
this document because I feel it's important to communicate the issues and
proposed solution. This way it's clear for everyone if we decide to take a
certain direction, and makes sure we're all on the same page. Here goes:
## current

Currently `dat-desktop` is a mix of server and client code, living in the
client:

``` txt
    ┌──────Electron window─────┐
 ┌ ─│        client code       |<┐
 |  │        server code       | |
 |  └──────────────────────────┘ |
ipc                            ipc
 |                              |
 |  ┌──────Electron server─────┐ |
 └ >│        boot process      |─┘
    └──────────────────────────┘
```

While this is very efficient to bootstrap, it mixes code in a way that's
entirely unique to electron and cannot be done in any other environment. It's a
bit of a special snowflake so to speak. Tools such as `browserify` and related
transforms cannot be applied to this particular architecture, and abstractions
cannot always easily be ported to other projects. One of the most pressing
issues is that the current design of `dat-elements` relies on `browserify`
transforms, and can thus not be consumed by the current architecture.
## proposed

Instead I want to propose we switch to a somewhat more traditional
architecture, providing a clearer devision between "client" and "server":

``` txt
    ┌──────Electron window─────┐
 ┌ ─│        client code       |<┐
 |  └──────────────────────────┘ |
ipc                            ipc
 |                              |
 |  ┌──────Electron server─────┐ |
 └ >│        server code       |─┘
    │        boot process      |
    └──────────────────────────┘
```

This has the advantage that the desktop app will have more overlap with our
other projects; and allow us to re-use elements without problem.
This would also allow us to start iterating on abstractions that can later be
moved out to separate packages. One particular example that comes to mind is an
API for `dat-cloud`.

If we were to separate the server from client, we'd have to call an API on the
server, from the client. I can imagine this would be similar to how `dat-land`
(or any other client) would call `dat-cloud` using an API library:

``` txt
    ┌──────Electron window─────┐
 ┌ ─│        client code       |<┐
 |  │        client API lib    | |
 |  └──────────────────────────┘ |
ipc                            ipc
 |                              |
 |  ┌──────Electron server─────┐ |
 |  │        server API lib    | |
 └ >│        server code       |─┘
    │        boot process      |
    └──────────────────────────┘
```

As the packages stabilize we could start moving them out, lowering the cost of
maintaining `dat-desktop` and creating more consumers of our APIs and related
libraries, improving their quality and thus also providing a better environment
for third party developers and future contributors.
## caveats

Moving to separate client from server is not without caveats. One particular
cost is that initial boot times would be increased. However, we can overcome
this by creating a static bundle for production and pointing to the bundle, and
additionally remove all asset rendering bits. This would also allow us to
optimize the bundle, improving performance.

A caveat for using `dat-desktop` as prototyping ground for other APIs is that
it would become a gravity well for other projects, potentially becoming
blocking for members involved. I think using a clear architecture (hi `choo`)
could to a certain extent help mitigate this, as code becomes less coupled and
individual people can take ownership of certain parts of the app - but we'd
have to figure out as a team how to do this. Given that this will not be
happening in the immediate future, we'll have enough time to think about the
approach and merits.
## wrapping up

I think it'd be greatly beneficial to move to a browserify based architecture
in the short term, and in the mid to long term use `dat-desktop` as prototyping
ground to start working on packages such as API libraries that will be used in
other environments.

**Comment by maxogden** [comment]
Thinking out loud, but it seems like the 'code smell' here is that while you don't need browserify to bundle your code for electron (since you can just require directly), you still need browserify to run browserify transforms. Maybe there's some unconsidered solution that involves either avoiding a dependency on browserify transforms or maybe calling transforms in special cases without needing to switch totally over to a bundled (client) workflow.

All in all though I think your proposal is very practical + agree keeping dev tools portable across environments is a high value feature.

**Comment by yoshuawuyts** [comment]
From IRC:
```txt
19:07:09 <@karissa> yoshuawuyts: yeah seems reasonable
```

**Comment by juliangruber** [comment]
@yoshuawuyts I can't seem to find the dat-elements repo anywhere, also curious why it needs browserify transforms. Maybe we can just do those transforms as part of the `npm publish` step so you can require them from anywhere?

**Comment by mafintosh** [comment]
@juliangruber https://github.com/datproject/dat-elements maybe?

**Comment by juliangruber** [comment]
@mafintosh ah, they aren't on npm yet, didn't see that repo. looking at https://github.com/datproject/dat-elements/blob/master/package.json#L6, even If we use browserify it's not going to run any transforms for this module, right?

**Comment by yoshuawuyts** [comment]
@juliangruber it will for https://github.com/yoshuawuyts/base-elements

**Comment by juliangruber** [comment]
@yoshuawuyts i guess moving this step into `prepublish` wouldn't work?

**Comment by yoshuawuyts** [comment]
browserify is now in the tree - we can improve on how we're compiling right now but this issue can be closed now - we're treating `electron` as a first-class third target in addition to node and browser, but also running `browserify` to enable optimizations and transforms. Yay! :sparkles:
