### ISSUE TITLE
npm install should install electron native modules correctly first time

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-desktop#74]
based on reading https://docs.npmjs.com/all#config i was hoping adding this to dat-desktop package.json would make npm install "just work" but it had no effect :( https://usercontent.irccloud-cdn.com/file/AoNdfyK3/Screen%20Shot%202016-11-02%20at%201.57.32%20PM.png

to fix it, @juliangruber came up with the idea of having `prebuild` respect the `config` property of package.json, which would solve the problem of needing a `npm run rebuild` script

**Comment by mafintosh** [comment]
@maxogden cool idea!

**Comment by clkao** [comment]
I am getting `Module version mismatch. Expected 50, got 48.` for the first `npm i`. It seems the second run recompiles things and made it work.

However if I tried to use linked `dat-js` for dev, the problem appears again.

**Comment by clkao** [comment]
probably related to https://github.com/electron/electron/issues/5851

**Comment by juliangruber** [comment]
@clkao hm weird, the postinstall script should run the rebuild script

**Comment by karissa** [comment]
Have you switched node versions since you installed dat-js?

**Comment by juliangruber** [comment]
pr here https://github.com/mafintosh/prebuild/pull/153
