### ISSUE TITLE
evaluate centralized-multidrive

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#90]
https://github.com/yoshuawuyts/centralized-multidrive

**Comment by yoshuawuyts** [comment]
I think https://github.com/yoshuawuyts/multidrive/
<https://github.com/yoshuawuyts/multidrive/tree/master> would be a better
fit for the current dat model

**Comment by yoshuawuyts** [comment]
we talked about this in person - `multidrive` is a useful idea, although the implementation is still quite exploratory; perhaps `multicore` might be an even better idea - but feel we've evaluated this topic for now (:
