### ISSUE TITLE
Hide Table Headers when table is empty

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#97]
Table headers should only show after at least one dat is created.

Current state:
![image](https://cloud.githubusercontent.com/assets/53684/20879327/58cf7696-bb27-11e6-9bbe-19af0b9a2e09.png)

**Comment by yoshuawuyts** [comment]
Feels like we'd need an empty state hmmmm ✨

**Comment by Kriesse** [comment]
@yoshuawuyts Yup :)
Can you set up an empty template for me that I can take from there and start styling?

![image](https://cloud.githubusercontent.com/assets/53684/20926806/67d3086a-bc12-11e6-960b-373484cd8386.png)

Also tracked here: https://github.com/datproject/dat-desktop/issues/68

**Comment by Kriesse** [comment]
Closing, tracking this in #68
